// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/proto/raid/CleanOutProto.proto

package com.dh.game.vo.raid;

public final class CleanOutProto {
  private CleanOutProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum RAIDTYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    NORMAL(0, 1),
    ELI(1, 2),
    ;
    
    public static final int NORMAL_VALUE = 1;
    public static final int ELI_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static RAIDTYPE valueOf(int value) {
      switch (value) {
        case 1: return NORMAL;
        case 2: return ELI;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<RAIDTYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RAIDTYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RAIDTYPE>() {
            public RAIDTYPE findValueByNumber(int number) {
              return RAIDTYPE.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.dh.game.vo.raid.CleanOutProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final RAIDTYPE[] VALUES = {
      NORMAL, ELI, 
    };
    
    public static RAIDTYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private RAIDTYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.dh.game.vo.raid.RAIDTYPE)
  }
  
  public interface CleanOutRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 raidid = 1;
    boolean hasRaidid();
    int getRaidid();
    
    // required .com.dh.game.vo.raid.RAIDTYPE raidtype = 2;
    boolean hasRaidtype();
    com.dh.game.vo.raid.CleanOutProto.RAIDTYPE getRaidtype();
    
    // optional int32 times = 3;
    boolean hasTimes();
    int getTimes();
  }
  public static final class CleanOutRequest extends
      com.google.protobuf.GeneratedMessage
      implements CleanOutRequestOrBuilder {
    // Use CleanOutRequest.newBuilder() to construct.
    private CleanOutRequest(Builder builder) {
      super(builder);
    }
    private CleanOutRequest(boolean noInit) {}
    
    private static final CleanOutRequest defaultInstance;
    public static CleanOutRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CleanOutRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_CleanOutRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_CleanOutRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 raidid = 1;
    public static final int RAIDID_FIELD_NUMBER = 1;
    private int raidid_;
    public boolean hasRaidid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getRaidid() {
      return raidid_;
    }
    
    // required .com.dh.game.vo.raid.RAIDTYPE raidtype = 2;
    public static final int RAIDTYPE_FIELD_NUMBER = 2;
    private com.dh.game.vo.raid.CleanOutProto.RAIDTYPE raidtype_;
    public boolean hasRaidtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.dh.game.vo.raid.CleanOutProto.RAIDTYPE getRaidtype() {
      return raidtype_;
    }
    
    // optional int32 times = 3;
    public static final int TIMES_FIELD_NUMBER = 3;
    private int times_;
    public boolean hasTimes() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getTimes() {
      return times_;
    }
    
    private void initFields() {
      raidid_ = 0;
      raidtype_ = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.NORMAL;
      times_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRaidid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRaidtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, raidid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, raidtype_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, times_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, raidid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, raidtype_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, times_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.raid.CleanOutProto.CleanOutRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.raid.CleanOutProto.CleanOutRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_CleanOutRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_CleanOutRequest_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.raid.CleanOutProto.CleanOutRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        raidid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        raidtype_ = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.NORMAL;
        bitField0_ = (bitField0_ & ~0x00000002);
        times_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.raid.CleanOutProto.CleanOutRequest.getDescriptor();
      }
      
      public com.dh.game.vo.raid.CleanOutProto.CleanOutRequest getDefaultInstanceForType() {
        return com.dh.game.vo.raid.CleanOutProto.CleanOutRequest.getDefaultInstance();
      }
      
      public com.dh.game.vo.raid.CleanOutProto.CleanOutRequest build() {
        com.dh.game.vo.raid.CleanOutProto.CleanOutRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.raid.CleanOutProto.CleanOutRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.raid.CleanOutProto.CleanOutRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.raid.CleanOutProto.CleanOutRequest buildPartial() {
        com.dh.game.vo.raid.CleanOutProto.CleanOutRequest result = new com.dh.game.vo.raid.CleanOutProto.CleanOutRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.raidid_ = raidid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.raidtype_ = raidtype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.times_ = times_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.raid.CleanOutProto.CleanOutRequest) {
          return mergeFrom((com.dh.game.vo.raid.CleanOutProto.CleanOutRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.raid.CleanOutProto.CleanOutRequest other) {
        if (other == com.dh.game.vo.raid.CleanOutProto.CleanOutRequest.getDefaultInstance()) return this;
        if (other.hasRaidid()) {
          setRaidid(other.getRaidid());
        }
        if (other.hasRaidtype()) {
          setRaidtype(other.getRaidtype());
        }
        if (other.hasTimes()) {
          setTimes(other.getTimes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRaidid()) {
          
          return false;
        }
        if (!hasRaidtype()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              raidid_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.dh.game.vo.raid.CleanOutProto.RAIDTYPE value = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                raidtype_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              times_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 raidid = 1;
      private int raidid_ ;
      public boolean hasRaidid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRaidid() {
        return raidid_;
      }
      public Builder setRaidid(int value) {
        bitField0_ |= 0x00000001;
        raidid_ = value;
        onChanged();
        return this;
      }
      public Builder clearRaidid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        raidid_ = 0;
        onChanged();
        return this;
      }
      
      // required .com.dh.game.vo.raid.RAIDTYPE raidtype = 2;
      private com.dh.game.vo.raid.CleanOutProto.RAIDTYPE raidtype_ = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.NORMAL;
      public boolean hasRaidtype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.dh.game.vo.raid.CleanOutProto.RAIDTYPE getRaidtype() {
        return raidtype_;
      }
      public Builder setRaidtype(com.dh.game.vo.raid.CleanOutProto.RAIDTYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        raidtype_ = value;
        onChanged();
        return this;
      }
      public Builder clearRaidtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        raidtype_ = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.NORMAL;
        onChanged();
        return this;
      }
      
      // optional int32 times = 3;
      private int times_ ;
      public boolean hasTimes() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getTimes() {
        return times_;
      }
      public Builder setTimes(int value) {
        bitField0_ |= 0x00000004;
        times_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        times_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.raid.CleanOutRequest)
    }
    
    static {
      defaultInstance = new CleanOutRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.raid.CleanOutRequest)
  }
  
  public interface CleanOutResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 raidid = 1;
    boolean hasRaidid();
    int getRaidid();
    
    // required .com.dh.game.vo.raid.RAIDTYPE raidtype = 2;
    boolean hasRaidtype();
    com.dh.game.vo.raid.CleanOutProto.RAIDTYPE getRaidtype();
    
    // repeated .com.dh.game.vo.raid.TimesResult timesResult = 3;
    java.util.List<com.dh.game.vo.raid.CleanOutProto.TimesResult> 
        getTimesResultList();
    com.dh.game.vo.raid.CleanOutProto.TimesResult getTimesResult(int index);
    int getTimesResultCount();
    java.util.List<? extends com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder> 
        getTimesResultOrBuilderList();
    com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder getTimesResultOrBuilder(
        int index);
  }
  public static final class CleanOutResponse extends
      com.google.protobuf.GeneratedMessage
      implements CleanOutResponseOrBuilder {
    // Use CleanOutResponse.newBuilder() to construct.
    private CleanOutResponse(Builder builder) {
      super(builder);
    }
    private CleanOutResponse(boolean noInit) {}
    
    private static final CleanOutResponse defaultInstance;
    public static CleanOutResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CleanOutResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_CleanOutResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_CleanOutResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 raidid = 1;
    public static final int RAIDID_FIELD_NUMBER = 1;
    private int raidid_;
    public boolean hasRaidid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getRaidid() {
      return raidid_;
    }
    
    // required .com.dh.game.vo.raid.RAIDTYPE raidtype = 2;
    public static final int RAIDTYPE_FIELD_NUMBER = 2;
    private com.dh.game.vo.raid.CleanOutProto.RAIDTYPE raidtype_;
    public boolean hasRaidtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.dh.game.vo.raid.CleanOutProto.RAIDTYPE getRaidtype() {
      return raidtype_;
    }
    
    // repeated .com.dh.game.vo.raid.TimesResult timesResult = 3;
    public static final int TIMESRESULT_FIELD_NUMBER = 3;
    private java.util.List<com.dh.game.vo.raid.CleanOutProto.TimesResult> timesResult_;
    public java.util.List<com.dh.game.vo.raid.CleanOutProto.TimesResult> getTimesResultList() {
      return timesResult_;
    }
    public java.util.List<? extends com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder> 
        getTimesResultOrBuilderList() {
      return timesResult_;
    }
    public int getTimesResultCount() {
      return timesResult_.size();
    }
    public com.dh.game.vo.raid.CleanOutProto.TimesResult getTimesResult(int index) {
      return timesResult_.get(index);
    }
    public com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder getTimesResultOrBuilder(
        int index) {
      return timesResult_.get(index);
    }
    
    private void initFields() {
      raidid_ = 0;
      raidtype_ = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.NORMAL;
      timesResult_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRaidid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRaidtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTimesResultCount(); i++) {
        if (!getTimesResult(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, raidid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, raidtype_.getNumber());
      }
      for (int i = 0; i < timesResult_.size(); i++) {
        output.writeMessage(3, timesResult_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, raidid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, raidtype_.getNumber());
      }
      for (int i = 0; i < timesResult_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, timesResult_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.CleanOutResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.raid.CleanOutProto.CleanOutResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.raid.CleanOutProto.CleanOutResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_CleanOutResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_CleanOutResponse_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.raid.CleanOutProto.CleanOutResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTimesResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        raidid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        raidtype_ = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.NORMAL;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (timesResultBuilder_ == null) {
          timesResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          timesResultBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.raid.CleanOutProto.CleanOutResponse.getDescriptor();
      }
      
      public com.dh.game.vo.raid.CleanOutProto.CleanOutResponse getDefaultInstanceForType() {
        return com.dh.game.vo.raid.CleanOutProto.CleanOutResponse.getDefaultInstance();
      }
      
      public com.dh.game.vo.raid.CleanOutProto.CleanOutResponse build() {
        com.dh.game.vo.raid.CleanOutProto.CleanOutResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.raid.CleanOutProto.CleanOutResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.raid.CleanOutProto.CleanOutResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.raid.CleanOutProto.CleanOutResponse buildPartial() {
        com.dh.game.vo.raid.CleanOutProto.CleanOutResponse result = new com.dh.game.vo.raid.CleanOutProto.CleanOutResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.raidid_ = raidid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.raidtype_ = raidtype_;
        if (timesResultBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            timesResult_ = java.util.Collections.unmodifiableList(timesResult_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.timesResult_ = timesResult_;
        } else {
          result.timesResult_ = timesResultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.raid.CleanOutProto.CleanOutResponse) {
          return mergeFrom((com.dh.game.vo.raid.CleanOutProto.CleanOutResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.raid.CleanOutProto.CleanOutResponse other) {
        if (other == com.dh.game.vo.raid.CleanOutProto.CleanOutResponse.getDefaultInstance()) return this;
        if (other.hasRaidid()) {
          setRaidid(other.getRaidid());
        }
        if (other.hasRaidtype()) {
          setRaidtype(other.getRaidtype());
        }
        if (timesResultBuilder_ == null) {
          if (!other.timesResult_.isEmpty()) {
            if (timesResult_.isEmpty()) {
              timesResult_ = other.timesResult_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTimesResultIsMutable();
              timesResult_.addAll(other.timesResult_);
            }
            onChanged();
          }
        } else {
          if (!other.timesResult_.isEmpty()) {
            if (timesResultBuilder_.isEmpty()) {
              timesResultBuilder_.dispose();
              timesResultBuilder_ = null;
              timesResult_ = other.timesResult_;
              bitField0_ = (bitField0_ & ~0x00000004);
              timesResultBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTimesResultFieldBuilder() : null;
            } else {
              timesResultBuilder_.addAllMessages(other.timesResult_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRaidid()) {
          
          return false;
        }
        if (!hasRaidtype()) {
          
          return false;
        }
        for (int i = 0; i < getTimesResultCount(); i++) {
          if (!getTimesResult(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              raidid_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.dh.game.vo.raid.CleanOutProto.RAIDTYPE value = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                raidtype_ = value;
              }
              break;
            }
            case 26: {
              com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder subBuilder = com.dh.game.vo.raid.CleanOutProto.TimesResult.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTimesResult(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 raidid = 1;
      private int raidid_ ;
      public boolean hasRaidid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRaidid() {
        return raidid_;
      }
      public Builder setRaidid(int value) {
        bitField0_ |= 0x00000001;
        raidid_ = value;
        onChanged();
        return this;
      }
      public Builder clearRaidid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        raidid_ = 0;
        onChanged();
        return this;
      }
      
      // required .com.dh.game.vo.raid.RAIDTYPE raidtype = 2;
      private com.dh.game.vo.raid.CleanOutProto.RAIDTYPE raidtype_ = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.NORMAL;
      public boolean hasRaidtype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.dh.game.vo.raid.CleanOutProto.RAIDTYPE getRaidtype() {
        return raidtype_;
      }
      public Builder setRaidtype(com.dh.game.vo.raid.CleanOutProto.RAIDTYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        raidtype_ = value;
        onChanged();
        return this;
      }
      public Builder clearRaidtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        raidtype_ = com.dh.game.vo.raid.CleanOutProto.RAIDTYPE.NORMAL;
        onChanged();
        return this;
      }
      
      // repeated .com.dh.game.vo.raid.TimesResult timesResult = 3;
      private java.util.List<com.dh.game.vo.raid.CleanOutProto.TimesResult> timesResult_ =
        java.util.Collections.emptyList();
      private void ensureTimesResultIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          timesResult_ = new java.util.ArrayList<com.dh.game.vo.raid.CleanOutProto.TimesResult>(timesResult_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.raid.CleanOutProto.TimesResult, com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder, com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder> timesResultBuilder_;
      
      public java.util.List<com.dh.game.vo.raid.CleanOutProto.TimesResult> getTimesResultList() {
        if (timesResultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(timesResult_);
        } else {
          return timesResultBuilder_.getMessageList();
        }
      }
      public int getTimesResultCount() {
        if (timesResultBuilder_ == null) {
          return timesResult_.size();
        } else {
          return timesResultBuilder_.getCount();
        }
      }
      public com.dh.game.vo.raid.CleanOutProto.TimesResult getTimesResult(int index) {
        if (timesResultBuilder_ == null) {
          return timesResult_.get(index);
        } else {
          return timesResultBuilder_.getMessage(index);
        }
      }
      public Builder setTimesResult(
          int index, com.dh.game.vo.raid.CleanOutProto.TimesResult value) {
        if (timesResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimesResultIsMutable();
          timesResult_.set(index, value);
          onChanged();
        } else {
          timesResultBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTimesResult(
          int index, com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder builderForValue) {
        if (timesResultBuilder_ == null) {
          ensureTimesResultIsMutable();
          timesResult_.set(index, builderForValue.build());
          onChanged();
        } else {
          timesResultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTimesResult(com.dh.game.vo.raid.CleanOutProto.TimesResult value) {
        if (timesResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimesResultIsMutable();
          timesResult_.add(value);
          onChanged();
        } else {
          timesResultBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTimesResult(
          int index, com.dh.game.vo.raid.CleanOutProto.TimesResult value) {
        if (timesResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimesResultIsMutable();
          timesResult_.add(index, value);
          onChanged();
        } else {
          timesResultBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTimesResult(
          com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder builderForValue) {
        if (timesResultBuilder_ == null) {
          ensureTimesResultIsMutable();
          timesResult_.add(builderForValue.build());
          onChanged();
        } else {
          timesResultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTimesResult(
          int index, com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder builderForValue) {
        if (timesResultBuilder_ == null) {
          ensureTimesResultIsMutable();
          timesResult_.add(index, builderForValue.build());
          onChanged();
        } else {
          timesResultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTimesResult(
          java.lang.Iterable<? extends com.dh.game.vo.raid.CleanOutProto.TimesResult> values) {
        if (timesResultBuilder_ == null) {
          ensureTimesResultIsMutable();
          super.addAll(values, timesResult_);
          onChanged();
        } else {
          timesResultBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTimesResult() {
        if (timesResultBuilder_ == null) {
          timesResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          timesResultBuilder_.clear();
        }
        return this;
      }
      public Builder removeTimesResult(int index) {
        if (timesResultBuilder_ == null) {
          ensureTimesResultIsMutable();
          timesResult_.remove(index);
          onChanged();
        } else {
          timesResultBuilder_.remove(index);
        }
        return this;
      }
      public com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder getTimesResultBuilder(
          int index) {
        return getTimesResultFieldBuilder().getBuilder(index);
      }
      public com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder getTimesResultOrBuilder(
          int index) {
        if (timesResultBuilder_ == null) {
          return timesResult_.get(index);  } else {
          return timesResultBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder> 
           getTimesResultOrBuilderList() {
        if (timesResultBuilder_ != null) {
          return timesResultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(timesResult_);
        }
      }
      public com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder addTimesResultBuilder() {
        return getTimesResultFieldBuilder().addBuilder(
            com.dh.game.vo.raid.CleanOutProto.TimesResult.getDefaultInstance());
      }
      public com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder addTimesResultBuilder(
          int index) {
        return getTimesResultFieldBuilder().addBuilder(
            index, com.dh.game.vo.raid.CleanOutProto.TimesResult.getDefaultInstance());
      }
      public java.util.List<com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder> 
           getTimesResultBuilderList() {
        return getTimesResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.raid.CleanOutProto.TimesResult, com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder, com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder> 
          getTimesResultFieldBuilder() {
        if (timesResultBuilder_ == null) {
          timesResultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dh.game.vo.raid.CleanOutProto.TimesResult, com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder, com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder>(
                  timesResult_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          timesResult_ = null;
        }
        return timesResultBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.raid.CleanOutResponse)
    }
    
    static {
      defaultInstance = new CleanOutResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.raid.CleanOutResponse)
  }
  
  public interface TimesResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 times = 1;
    boolean hasTimes();
    int getTimes();
    
    // repeated .com.dh.game.vo.raid.RaidRewardinfo raidRewardinfo = 2;
    java.util.List<com.dh.game.vo.raid.RaidProto.RaidRewardinfo> 
        getRaidRewardinfoList();
    com.dh.game.vo.raid.RaidProto.RaidRewardinfo getRaidRewardinfo(int index);
    int getRaidRewardinfoCount();
    java.util.List<? extends com.dh.game.vo.raid.RaidProto.RaidRewardinfoOrBuilder> 
        getRaidRewardinfoOrBuilderList();
    com.dh.game.vo.raid.RaidProto.RaidRewardinfoOrBuilder getRaidRewardinfoOrBuilder(
        int index);
  }
  public static final class TimesResult extends
      com.google.protobuf.GeneratedMessage
      implements TimesResultOrBuilder {
    // Use TimesResult.newBuilder() to construct.
    private TimesResult(Builder builder) {
      super(builder);
    }
    private TimesResult(boolean noInit) {}
    
    private static final TimesResult defaultInstance;
    public static TimesResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public TimesResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_TimesResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_TimesResult_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 times = 1;
    public static final int TIMES_FIELD_NUMBER = 1;
    private int times_;
    public boolean hasTimes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTimes() {
      return times_;
    }
    
    // repeated .com.dh.game.vo.raid.RaidRewardinfo raidRewardinfo = 2;
    public static final int RAIDREWARDINFO_FIELD_NUMBER = 2;
    private java.util.List<com.dh.game.vo.raid.RaidProto.RaidRewardinfo> raidRewardinfo_;
    public java.util.List<com.dh.game.vo.raid.RaidProto.RaidRewardinfo> getRaidRewardinfoList() {
      return raidRewardinfo_;
    }
    public java.util.List<? extends com.dh.game.vo.raid.RaidProto.RaidRewardinfoOrBuilder> 
        getRaidRewardinfoOrBuilderList() {
      return raidRewardinfo_;
    }
    public int getRaidRewardinfoCount() {
      return raidRewardinfo_.size();
    }
    public com.dh.game.vo.raid.RaidProto.RaidRewardinfo getRaidRewardinfo(int index) {
      return raidRewardinfo_.get(index);
    }
    public com.dh.game.vo.raid.RaidProto.RaidRewardinfoOrBuilder getRaidRewardinfoOrBuilder(
        int index) {
      return raidRewardinfo_.get(index);
    }
    
    private void initFields() {
      times_ = 0;
      raidRewardinfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRaidRewardinfoCount(); i++) {
        if (!getRaidRewardinfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, times_);
      }
      for (int i = 0; i < raidRewardinfo_.size(); i++) {
        output.writeMessage(2, raidRewardinfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, times_);
      }
      for (int i = 0; i < raidRewardinfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, raidRewardinfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.raid.CleanOutProto.TimesResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.raid.CleanOutProto.TimesResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.raid.CleanOutProto.TimesResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_TimesResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.raid.CleanOutProto.internal_static_com_dh_game_vo_raid_TimesResult_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.raid.CleanOutProto.TimesResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRaidRewardinfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        times_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (raidRewardinfoBuilder_ == null) {
          raidRewardinfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          raidRewardinfoBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.raid.CleanOutProto.TimesResult.getDescriptor();
      }
      
      public com.dh.game.vo.raid.CleanOutProto.TimesResult getDefaultInstanceForType() {
        return com.dh.game.vo.raid.CleanOutProto.TimesResult.getDefaultInstance();
      }
      
      public com.dh.game.vo.raid.CleanOutProto.TimesResult build() {
        com.dh.game.vo.raid.CleanOutProto.TimesResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.raid.CleanOutProto.TimesResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.raid.CleanOutProto.TimesResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.raid.CleanOutProto.TimesResult buildPartial() {
        com.dh.game.vo.raid.CleanOutProto.TimesResult result = new com.dh.game.vo.raid.CleanOutProto.TimesResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.times_ = times_;
        if (raidRewardinfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            raidRewardinfo_ = java.util.Collections.unmodifiableList(raidRewardinfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.raidRewardinfo_ = raidRewardinfo_;
        } else {
          result.raidRewardinfo_ = raidRewardinfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.raid.CleanOutProto.TimesResult) {
          return mergeFrom((com.dh.game.vo.raid.CleanOutProto.TimesResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.raid.CleanOutProto.TimesResult other) {
        if (other == com.dh.game.vo.raid.CleanOutProto.TimesResult.getDefaultInstance()) return this;
        if (other.hasTimes()) {
          setTimes(other.getTimes());
        }
        if (raidRewardinfoBuilder_ == null) {
          if (!other.raidRewardinfo_.isEmpty()) {
            if (raidRewardinfo_.isEmpty()) {
              raidRewardinfo_ = other.raidRewardinfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRaidRewardinfoIsMutable();
              raidRewardinfo_.addAll(other.raidRewardinfo_);
            }
            onChanged();
          }
        } else {
          if (!other.raidRewardinfo_.isEmpty()) {
            if (raidRewardinfoBuilder_.isEmpty()) {
              raidRewardinfoBuilder_.dispose();
              raidRewardinfoBuilder_ = null;
              raidRewardinfo_ = other.raidRewardinfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              raidRewardinfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRaidRewardinfoFieldBuilder() : null;
            } else {
              raidRewardinfoBuilder_.addAllMessages(other.raidRewardinfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimes()) {
          
          return false;
        }
        for (int i = 0; i < getRaidRewardinfoCount(); i++) {
          if (!getRaidRewardinfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              times_ = input.readInt32();
              break;
            }
            case 18: {
              com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder subBuilder = com.dh.game.vo.raid.RaidProto.RaidRewardinfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRaidRewardinfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 times = 1;
      private int times_ ;
      public boolean hasTimes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTimes() {
        return times_;
      }
      public Builder setTimes(int value) {
        bitField0_ |= 0x00000001;
        times_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        times_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.dh.game.vo.raid.RaidRewardinfo raidRewardinfo = 2;
      private java.util.List<com.dh.game.vo.raid.RaidProto.RaidRewardinfo> raidRewardinfo_ =
        java.util.Collections.emptyList();
      private void ensureRaidRewardinfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          raidRewardinfo_ = new java.util.ArrayList<com.dh.game.vo.raid.RaidProto.RaidRewardinfo>(raidRewardinfo_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.raid.RaidProto.RaidRewardinfo, com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder, com.dh.game.vo.raid.RaidProto.RaidRewardinfoOrBuilder> raidRewardinfoBuilder_;
      
      public java.util.List<com.dh.game.vo.raid.RaidProto.RaidRewardinfo> getRaidRewardinfoList() {
        if (raidRewardinfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(raidRewardinfo_);
        } else {
          return raidRewardinfoBuilder_.getMessageList();
        }
      }
      public int getRaidRewardinfoCount() {
        if (raidRewardinfoBuilder_ == null) {
          return raidRewardinfo_.size();
        } else {
          return raidRewardinfoBuilder_.getCount();
        }
      }
      public com.dh.game.vo.raid.RaidProto.RaidRewardinfo getRaidRewardinfo(int index) {
        if (raidRewardinfoBuilder_ == null) {
          return raidRewardinfo_.get(index);
        } else {
          return raidRewardinfoBuilder_.getMessage(index);
        }
      }
      public Builder setRaidRewardinfo(
          int index, com.dh.game.vo.raid.RaidProto.RaidRewardinfo value) {
        if (raidRewardinfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRaidRewardinfoIsMutable();
          raidRewardinfo_.set(index, value);
          onChanged();
        } else {
          raidRewardinfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRaidRewardinfo(
          int index, com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder builderForValue) {
        if (raidRewardinfoBuilder_ == null) {
          ensureRaidRewardinfoIsMutable();
          raidRewardinfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          raidRewardinfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRaidRewardinfo(com.dh.game.vo.raid.RaidProto.RaidRewardinfo value) {
        if (raidRewardinfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRaidRewardinfoIsMutable();
          raidRewardinfo_.add(value);
          onChanged();
        } else {
          raidRewardinfoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRaidRewardinfo(
          int index, com.dh.game.vo.raid.RaidProto.RaidRewardinfo value) {
        if (raidRewardinfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRaidRewardinfoIsMutable();
          raidRewardinfo_.add(index, value);
          onChanged();
        } else {
          raidRewardinfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRaidRewardinfo(
          com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder builderForValue) {
        if (raidRewardinfoBuilder_ == null) {
          ensureRaidRewardinfoIsMutable();
          raidRewardinfo_.add(builderForValue.build());
          onChanged();
        } else {
          raidRewardinfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRaidRewardinfo(
          int index, com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder builderForValue) {
        if (raidRewardinfoBuilder_ == null) {
          ensureRaidRewardinfoIsMutable();
          raidRewardinfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          raidRewardinfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRaidRewardinfo(
          java.lang.Iterable<? extends com.dh.game.vo.raid.RaidProto.RaidRewardinfo> values) {
        if (raidRewardinfoBuilder_ == null) {
          ensureRaidRewardinfoIsMutable();
          super.addAll(values, raidRewardinfo_);
          onChanged();
        } else {
          raidRewardinfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRaidRewardinfo() {
        if (raidRewardinfoBuilder_ == null) {
          raidRewardinfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          raidRewardinfoBuilder_.clear();
        }
        return this;
      }
      public Builder removeRaidRewardinfo(int index) {
        if (raidRewardinfoBuilder_ == null) {
          ensureRaidRewardinfoIsMutable();
          raidRewardinfo_.remove(index);
          onChanged();
        } else {
          raidRewardinfoBuilder_.remove(index);
        }
        return this;
      }
      public com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder getRaidRewardinfoBuilder(
          int index) {
        return getRaidRewardinfoFieldBuilder().getBuilder(index);
      }
      public com.dh.game.vo.raid.RaidProto.RaidRewardinfoOrBuilder getRaidRewardinfoOrBuilder(
          int index) {
        if (raidRewardinfoBuilder_ == null) {
          return raidRewardinfo_.get(index);  } else {
          return raidRewardinfoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.dh.game.vo.raid.RaidProto.RaidRewardinfoOrBuilder> 
           getRaidRewardinfoOrBuilderList() {
        if (raidRewardinfoBuilder_ != null) {
          return raidRewardinfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(raidRewardinfo_);
        }
      }
      public com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder addRaidRewardinfoBuilder() {
        return getRaidRewardinfoFieldBuilder().addBuilder(
            com.dh.game.vo.raid.RaidProto.RaidRewardinfo.getDefaultInstance());
      }
      public com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder addRaidRewardinfoBuilder(
          int index) {
        return getRaidRewardinfoFieldBuilder().addBuilder(
            index, com.dh.game.vo.raid.RaidProto.RaidRewardinfo.getDefaultInstance());
      }
      public java.util.List<com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder> 
           getRaidRewardinfoBuilderList() {
        return getRaidRewardinfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.raid.RaidProto.RaidRewardinfo, com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder, com.dh.game.vo.raid.RaidProto.RaidRewardinfoOrBuilder> 
          getRaidRewardinfoFieldBuilder() {
        if (raidRewardinfoBuilder_ == null) {
          raidRewardinfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dh.game.vo.raid.RaidProto.RaidRewardinfo, com.dh.game.vo.raid.RaidProto.RaidRewardinfo.Builder, com.dh.game.vo.raid.RaidProto.RaidRewardinfoOrBuilder>(
                  raidRewardinfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          raidRewardinfo_ = null;
        }
        return raidRewardinfoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.raid.TimesResult)
    }
    
    static {
      defaultInstance = new TimesResult(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.raid.TimesResult)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_raid_CleanOutRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_raid_CleanOutRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_raid_CleanOutResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_raid_CleanOutResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_raid_TimesResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_raid_TimesResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"com/proto/raid/CleanOutProto.proto\022\023co" +
      "m.dh.game.vo.raid\032\036com/proto/raid/RaidPr" +
      "oto.proto\"a\n\017CleanOutRequest\022\016\n\006raidid\030\001" +
      " \002(\005\022/\n\010raidtype\030\002 \002(\0162\035.com.dh.game.vo." +
      "raid.RAIDTYPE\022\r\n\005times\030\003 \001(\005\"\212\001\n\020CleanOu" +
      "tResponse\022\016\n\006raidid\030\001 \002(\005\022/\n\010raidtype\030\002 " +
      "\002(\0162\035.com.dh.game.vo.raid.RAIDTYPE\0225\n\013ti" +
      "mesResult\030\003 \003(\0132 .com.dh.game.vo.raid.Ti" +
      "mesResult\"Y\n\013TimesResult\022\r\n\005times\030\001 \002(\005\022" +
      ";\n\016raidRewardinfo\030\002 \003(\0132#.com.dh.game.vo",
      ".raid.RaidRewardinfo*\037\n\010RAIDTYPE\022\n\n\006NORM" +
      "AL\020\001\022\007\n\003ELI\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dh_game_vo_raid_CleanOutRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dh_game_vo_raid_CleanOutRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_raid_CleanOutRequest_descriptor,
              new java.lang.String[] { "Raidid", "Raidtype", "Times", },
              com.dh.game.vo.raid.CleanOutProto.CleanOutRequest.class,
              com.dh.game.vo.raid.CleanOutProto.CleanOutRequest.Builder.class);
          internal_static_com_dh_game_vo_raid_CleanOutResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dh_game_vo_raid_CleanOutResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_raid_CleanOutResponse_descriptor,
              new java.lang.String[] { "Raidid", "Raidtype", "TimesResult", },
              com.dh.game.vo.raid.CleanOutProto.CleanOutResponse.class,
              com.dh.game.vo.raid.CleanOutProto.CleanOutResponse.Builder.class);
          internal_static_com_dh_game_vo_raid_TimesResult_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_dh_game_vo_raid_TimesResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_raid_TimesResult_descriptor,
              new java.lang.String[] { "Times", "RaidRewardinfo", },
              com.dh.game.vo.raid.CleanOutProto.TimesResult.class,
              com.dh.game.vo.raid.CleanOutProto.TimesResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dh.game.vo.raid.RaidProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
