// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/proto/shop/GrabProto.proto

package com.dh.game.vo.grab;

public final class GrabProto {
  private GrabProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum RATETYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    LOW(0, 1),
    MEDIUM(1, 2),
    HIGH(2, 3),
    HIGHER(3, 4),
    HIGHEST(4, 5),
    ;
    
    public static final int LOW_VALUE = 1;
    public static final int MEDIUM_VALUE = 2;
    public static final int HIGH_VALUE = 3;
    public static final int HIGHER_VALUE = 4;
    public static final int HIGHEST_VALUE = 5;
    
    
    public final int getNumber() { return value; }
    
    public static RATETYPE valueOf(int value) {
      switch (value) {
        case 1: return LOW;
        case 2: return MEDIUM;
        case 3: return HIGH;
        case 4: return HIGHER;
        case 5: return HIGHEST;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<RATETYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RATETYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RATETYPE>() {
            public RATETYPE findValueByNumber(int number) {
              return RATETYPE.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.dh.game.vo.grab.GrabProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final RATETYPE[] VALUES = {
      LOW, MEDIUM, HIGH, HIGHER, HIGHEST, 
    };
    
    public static RATETYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private RATETYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.dh.game.vo.grab.RATETYPE)
  }
  
  public interface GrabListRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 itemCfgid = 1;
    boolean hasItemCfgid();
    int getItemCfgid();
  }
  public static final class GrabListRequest extends
      com.google.protobuf.GeneratedMessage
      implements GrabListRequestOrBuilder {
    // Use GrabListRequest.newBuilder() to construct.
    private GrabListRequest(Builder builder) {
      super(builder);
    }
    private GrabListRequest(boolean noInit) {}
    
    private static final GrabListRequest defaultInstance;
    public static GrabListRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public GrabListRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabListRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabListRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 itemCfgid = 1;
    public static final int ITEMCFGID_FIELD_NUMBER = 1;
    private int itemCfgid_;
    public boolean hasItemCfgid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getItemCfgid() {
      return itemCfgid_;
    }
    
    private void initFields() {
      itemCfgid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasItemCfgid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, itemCfgid_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemCfgid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.grab.GrabProto.GrabListRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.grab.GrabProto.GrabListRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabListRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabListRequest_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.grab.GrabProto.GrabListRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        itemCfgid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.grab.GrabProto.GrabListRequest.getDescriptor();
      }
      
      public com.dh.game.vo.grab.GrabProto.GrabListRequest getDefaultInstanceForType() {
        return com.dh.game.vo.grab.GrabProto.GrabListRequest.getDefaultInstance();
      }
      
      public com.dh.game.vo.grab.GrabProto.GrabListRequest build() {
        com.dh.game.vo.grab.GrabProto.GrabListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.grab.GrabProto.GrabListRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.grab.GrabProto.GrabListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.grab.GrabProto.GrabListRequest buildPartial() {
        com.dh.game.vo.grab.GrabProto.GrabListRequest result = new com.dh.game.vo.grab.GrabProto.GrabListRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemCfgid_ = itemCfgid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.grab.GrabProto.GrabListRequest) {
          return mergeFrom((com.dh.game.vo.grab.GrabProto.GrabListRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.grab.GrabProto.GrabListRequest other) {
        if (other == com.dh.game.vo.grab.GrabProto.GrabListRequest.getDefaultInstance()) return this;
        if (other.hasItemCfgid()) {
          setItemCfgid(other.getItemCfgid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasItemCfgid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              itemCfgid_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 itemCfgid = 1;
      private int itemCfgid_ ;
      public boolean hasItemCfgid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getItemCfgid() {
        return itemCfgid_;
      }
      public Builder setItemCfgid(int value) {
        bitField0_ |= 0x00000001;
        itemCfgid_ = value;
        onChanged();
        return this;
      }
      public Builder clearItemCfgid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemCfgid_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.grab.GrabListRequest)
    }
    
    static {
      defaultInstance = new GrabListRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.grab.GrabListRequest)
  }
  
  public interface GrabListResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 itemCfgid = 1;
    boolean hasItemCfgid();
    int getItemCfgid();
    
    // repeated .com.dh.game.vo.grab.GrabRoleInfo grabRoleInfo = 2;
    java.util.List<com.dh.game.vo.grab.GrabProto.GrabRoleInfo> 
        getGrabRoleInfoList();
    com.dh.game.vo.grab.GrabProto.GrabRoleInfo getGrabRoleInfo(int index);
    int getGrabRoleInfoCount();
    java.util.List<? extends com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder> 
        getGrabRoleInfoOrBuilderList();
    com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder getGrabRoleInfoOrBuilder(
        int index);
    
    // required int32 costpvp = 3;
    boolean hasCostpvp();
    int getCostpvp();
    
    // required int32 remaintime = 4;
    boolean hasRemaintime();
    int getRemaintime();
    
    // required int32 changeEnempvp = 5;
    boolean hasChangeEnempvp();
    int getChangeEnempvp();
  }
  public static final class GrabListResponse extends
      com.google.protobuf.GeneratedMessage
      implements GrabListResponseOrBuilder {
    // Use GrabListResponse.newBuilder() to construct.
    private GrabListResponse(Builder builder) {
      super(builder);
    }
    private GrabListResponse(boolean noInit) {}
    
    private static final GrabListResponse defaultInstance;
    public static GrabListResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public GrabListResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabListResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabListResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 itemCfgid = 1;
    public static final int ITEMCFGID_FIELD_NUMBER = 1;
    private int itemCfgid_;
    public boolean hasItemCfgid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getItemCfgid() {
      return itemCfgid_;
    }
    
    // repeated .com.dh.game.vo.grab.GrabRoleInfo grabRoleInfo = 2;
    public static final int GRABROLEINFO_FIELD_NUMBER = 2;
    private java.util.List<com.dh.game.vo.grab.GrabProto.GrabRoleInfo> grabRoleInfo_;
    public java.util.List<com.dh.game.vo.grab.GrabProto.GrabRoleInfo> getGrabRoleInfoList() {
      return grabRoleInfo_;
    }
    public java.util.List<? extends com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder> 
        getGrabRoleInfoOrBuilderList() {
      return grabRoleInfo_;
    }
    public int getGrabRoleInfoCount() {
      return grabRoleInfo_.size();
    }
    public com.dh.game.vo.grab.GrabProto.GrabRoleInfo getGrabRoleInfo(int index) {
      return grabRoleInfo_.get(index);
    }
    public com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder getGrabRoleInfoOrBuilder(
        int index) {
      return grabRoleInfo_.get(index);
    }
    
    // required int32 costpvp = 3;
    public static final int COSTPVP_FIELD_NUMBER = 3;
    private int costpvp_;
    public boolean hasCostpvp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCostpvp() {
      return costpvp_;
    }
    
    // required int32 remaintime = 4;
    public static final int REMAINTIME_FIELD_NUMBER = 4;
    private int remaintime_;
    public boolean hasRemaintime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getRemaintime() {
      return remaintime_;
    }
    
    // required int32 changeEnempvp = 5;
    public static final int CHANGEENEMPVP_FIELD_NUMBER = 5;
    private int changeEnempvp_;
    public boolean hasChangeEnempvp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getChangeEnempvp() {
      return changeEnempvp_;
    }
    
    private void initFields() {
      itemCfgid_ = 0;
      grabRoleInfo_ = java.util.Collections.emptyList();
      costpvp_ = 0;
      remaintime_ = 0;
      changeEnempvp_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasItemCfgid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCostpvp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRemaintime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChangeEnempvp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getGrabRoleInfoCount(); i++) {
        if (!getGrabRoleInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, itemCfgid_);
      }
      for (int i = 0; i < grabRoleInfo_.size(); i++) {
        output.writeMessage(2, grabRoleInfo_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, costpvp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, remaintime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, changeEnempvp_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemCfgid_);
      }
      for (int i = 0; i < grabRoleInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, grabRoleInfo_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, costpvp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, remaintime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, changeEnempvp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.grab.GrabProto.GrabListResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.grab.GrabProto.GrabListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabListResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabListResponse_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.grab.GrabProto.GrabListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGrabRoleInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        itemCfgid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (grabRoleInfoBuilder_ == null) {
          grabRoleInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          grabRoleInfoBuilder_.clear();
        }
        costpvp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        remaintime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        changeEnempvp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.grab.GrabProto.GrabListResponse.getDescriptor();
      }
      
      public com.dh.game.vo.grab.GrabProto.GrabListResponse getDefaultInstanceForType() {
        return com.dh.game.vo.grab.GrabProto.GrabListResponse.getDefaultInstance();
      }
      
      public com.dh.game.vo.grab.GrabProto.GrabListResponse build() {
        com.dh.game.vo.grab.GrabProto.GrabListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.grab.GrabProto.GrabListResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.grab.GrabProto.GrabListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.grab.GrabProto.GrabListResponse buildPartial() {
        com.dh.game.vo.grab.GrabProto.GrabListResponse result = new com.dh.game.vo.grab.GrabProto.GrabListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemCfgid_ = itemCfgid_;
        if (grabRoleInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            grabRoleInfo_ = java.util.Collections.unmodifiableList(grabRoleInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.grabRoleInfo_ = grabRoleInfo_;
        } else {
          result.grabRoleInfo_ = grabRoleInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.costpvp_ = costpvp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.remaintime_ = remaintime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.changeEnempvp_ = changeEnempvp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.grab.GrabProto.GrabListResponse) {
          return mergeFrom((com.dh.game.vo.grab.GrabProto.GrabListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.grab.GrabProto.GrabListResponse other) {
        if (other == com.dh.game.vo.grab.GrabProto.GrabListResponse.getDefaultInstance()) return this;
        if (other.hasItemCfgid()) {
          setItemCfgid(other.getItemCfgid());
        }
        if (grabRoleInfoBuilder_ == null) {
          if (!other.grabRoleInfo_.isEmpty()) {
            if (grabRoleInfo_.isEmpty()) {
              grabRoleInfo_ = other.grabRoleInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureGrabRoleInfoIsMutable();
              grabRoleInfo_.addAll(other.grabRoleInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.grabRoleInfo_.isEmpty()) {
            if (grabRoleInfoBuilder_.isEmpty()) {
              grabRoleInfoBuilder_.dispose();
              grabRoleInfoBuilder_ = null;
              grabRoleInfo_ = other.grabRoleInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              grabRoleInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGrabRoleInfoFieldBuilder() : null;
            } else {
              grabRoleInfoBuilder_.addAllMessages(other.grabRoleInfo_);
            }
          }
        }
        if (other.hasCostpvp()) {
          setCostpvp(other.getCostpvp());
        }
        if (other.hasRemaintime()) {
          setRemaintime(other.getRemaintime());
        }
        if (other.hasChangeEnempvp()) {
          setChangeEnempvp(other.getChangeEnempvp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasItemCfgid()) {
          
          return false;
        }
        if (!hasCostpvp()) {
          
          return false;
        }
        if (!hasRemaintime()) {
          
          return false;
        }
        if (!hasChangeEnempvp()) {
          
          return false;
        }
        for (int i = 0; i < getGrabRoleInfoCount(); i++) {
          if (!getGrabRoleInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              itemCfgid_ = input.readInt32();
              break;
            }
            case 18: {
              com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder subBuilder = com.dh.game.vo.grab.GrabProto.GrabRoleInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGrabRoleInfo(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              costpvp_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              remaintime_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              changeEnempvp_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 itemCfgid = 1;
      private int itemCfgid_ ;
      public boolean hasItemCfgid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getItemCfgid() {
        return itemCfgid_;
      }
      public Builder setItemCfgid(int value) {
        bitField0_ |= 0x00000001;
        itemCfgid_ = value;
        onChanged();
        return this;
      }
      public Builder clearItemCfgid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemCfgid_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.dh.game.vo.grab.GrabRoleInfo grabRoleInfo = 2;
      private java.util.List<com.dh.game.vo.grab.GrabProto.GrabRoleInfo> grabRoleInfo_ =
        java.util.Collections.emptyList();
      private void ensureGrabRoleInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          grabRoleInfo_ = new java.util.ArrayList<com.dh.game.vo.grab.GrabProto.GrabRoleInfo>(grabRoleInfo_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.grab.GrabProto.GrabRoleInfo, com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder, com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder> grabRoleInfoBuilder_;
      
      public java.util.List<com.dh.game.vo.grab.GrabProto.GrabRoleInfo> getGrabRoleInfoList() {
        if (grabRoleInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(grabRoleInfo_);
        } else {
          return grabRoleInfoBuilder_.getMessageList();
        }
      }
      public int getGrabRoleInfoCount() {
        if (grabRoleInfoBuilder_ == null) {
          return grabRoleInfo_.size();
        } else {
          return grabRoleInfoBuilder_.getCount();
        }
      }
      public com.dh.game.vo.grab.GrabProto.GrabRoleInfo getGrabRoleInfo(int index) {
        if (grabRoleInfoBuilder_ == null) {
          return grabRoleInfo_.get(index);
        } else {
          return grabRoleInfoBuilder_.getMessage(index);
        }
      }
      public Builder setGrabRoleInfo(
          int index, com.dh.game.vo.grab.GrabProto.GrabRoleInfo value) {
        if (grabRoleInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGrabRoleInfoIsMutable();
          grabRoleInfo_.set(index, value);
          onChanged();
        } else {
          grabRoleInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGrabRoleInfo(
          int index, com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder builderForValue) {
        if (grabRoleInfoBuilder_ == null) {
          ensureGrabRoleInfoIsMutable();
          grabRoleInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          grabRoleInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGrabRoleInfo(com.dh.game.vo.grab.GrabProto.GrabRoleInfo value) {
        if (grabRoleInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGrabRoleInfoIsMutable();
          grabRoleInfo_.add(value);
          onChanged();
        } else {
          grabRoleInfoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGrabRoleInfo(
          int index, com.dh.game.vo.grab.GrabProto.GrabRoleInfo value) {
        if (grabRoleInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGrabRoleInfoIsMutable();
          grabRoleInfo_.add(index, value);
          onChanged();
        } else {
          grabRoleInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGrabRoleInfo(
          com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder builderForValue) {
        if (grabRoleInfoBuilder_ == null) {
          ensureGrabRoleInfoIsMutable();
          grabRoleInfo_.add(builderForValue.build());
          onChanged();
        } else {
          grabRoleInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGrabRoleInfo(
          int index, com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder builderForValue) {
        if (grabRoleInfoBuilder_ == null) {
          ensureGrabRoleInfoIsMutable();
          grabRoleInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          grabRoleInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGrabRoleInfo(
          java.lang.Iterable<? extends com.dh.game.vo.grab.GrabProto.GrabRoleInfo> values) {
        if (grabRoleInfoBuilder_ == null) {
          ensureGrabRoleInfoIsMutable();
          super.addAll(values, grabRoleInfo_);
          onChanged();
        } else {
          grabRoleInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGrabRoleInfo() {
        if (grabRoleInfoBuilder_ == null) {
          grabRoleInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          grabRoleInfoBuilder_.clear();
        }
        return this;
      }
      public Builder removeGrabRoleInfo(int index) {
        if (grabRoleInfoBuilder_ == null) {
          ensureGrabRoleInfoIsMutable();
          grabRoleInfo_.remove(index);
          onChanged();
        } else {
          grabRoleInfoBuilder_.remove(index);
        }
        return this;
      }
      public com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder getGrabRoleInfoBuilder(
          int index) {
        return getGrabRoleInfoFieldBuilder().getBuilder(index);
      }
      public com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder getGrabRoleInfoOrBuilder(
          int index) {
        if (grabRoleInfoBuilder_ == null) {
          return grabRoleInfo_.get(index);  } else {
          return grabRoleInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder> 
           getGrabRoleInfoOrBuilderList() {
        if (grabRoleInfoBuilder_ != null) {
          return grabRoleInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(grabRoleInfo_);
        }
      }
      public com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder addGrabRoleInfoBuilder() {
        return getGrabRoleInfoFieldBuilder().addBuilder(
            com.dh.game.vo.grab.GrabProto.GrabRoleInfo.getDefaultInstance());
      }
      public com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder addGrabRoleInfoBuilder(
          int index) {
        return getGrabRoleInfoFieldBuilder().addBuilder(
            index, com.dh.game.vo.grab.GrabProto.GrabRoleInfo.getDefaultInstance());
      }
      public java.util.List<com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder> 
           getGrabRoleInfoBuilderList() {
        return getGrabRoleInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.grab.GrabProto.GrabRoleInfo, com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder, com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder> 
          getGrabRoleInfoFieldBuilder() {
        if (grabRoleInfoBuilder_ == null) {
          grabRoleInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dh.game.vo.grab.GrabProto.GrabRoleInfo, com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder, com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder>(
                  grabRoleInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          grabRoleInfo_ = null;
        }
        return grabRoleInfoBuilder_;
      }
      
      // required int32 costpvp = 3;
      private int costpvp_ ;
      public boolean hasCostpvp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getCostpvp() {
        return costpvp_;
      }
      public Builder setCostpvp(int value) {
        bitField0_ |= 0x00000004;
        costpvp_ = value;
        onChanged();
        return this;
      }
      public Builder clearCostpvp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        costpvp_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 remaintime = 4;
      private int remaintime_ ;
      public boolean hasRemaintime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getRemaintime() {
        return remaintime_;
      }
      public Builder setRemaintime(int value) {
        bitField0_ |= 0x00000008;
        remaintime_ = value;
        onChanged();
        return this;
      }
      public Builder clearRemaintime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        remaintime_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 changeEnempvp = 5;
      private int changeEnempvp_ ;
      public boolean hasChangeEnempvp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getChangeEnempvp() {
        return changeEnempvp_;
      }
      public Builder setChangeEnempvp(int value) {
        bitField0_ |= 0x00000010;
        changeEnempvp_ = value;
        onChanged();
        return this;
      }
      public Builder clearChangeEnempvp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        changeEnempvp_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.grab.GrabListResponse)
    }
    
    static {
      defaultInstance = new GrabListResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.grab.GrabListResponse)
  }
  
  public interface GrabRoleInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 playerId = 1;
    boolean hasPlayerId();
    int getPlayerId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // required int32 combat = 3;
    boolean hasCombat();
    int getCombat();
    
    // required .com.dh.game.vo.grab.RATETYPE rate = 4;
    boolean hasRate();
    com.dh.game.vo.grab.GrabProto.RATETYPE getRate();
    
    // repeated .com.dh.game.vo.FinalHero finalHero = 5;
    java.util.List<com.dh.game.vo.BaseProto.FinalHero> 
        getFinalHeroList();
    com.dh.game.vo.BaseProto.FinalHero getFinalHero(int index);
    int getFinalHeroCount();
    java.util.List<? extends com.dh.game.vo.BaseProto.FinalHeroOrBuilder> 
        getFinalHeroOrBuilderList();
    com.dh.game.vo.BaseProto.FinalHeroOrBuilder getFinalHeroOrBuilder(
        int index);
  }
  public static final class GrabRoleInfo extends
      com.google.protobuf.GeneratedMessage
      implements GrabRoleInfoOrBuilder {
    // Use GrabRoleInfo.newBuilder() to construct.
    private GrabRoleInfo(Builder builder) {
      super(builder);
    }
    private GrabRoleInfo(boolean noInit) {}
    
    private static final GrabRoleInfo defaultInstance;
    public static GrabRoleInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public GrabRoleInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabRoleInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabRoleInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPlayerId() {
      return playerId_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 combat = 3;
    public static final int COMBAT_FIELD_NUMBER = 3;
    private int combat_;
    public boolean hasCombat() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getCombat() {
      return combat_;
    }
    
    // required .com.dh.game.vo.grab.RATETYPE rate = 4;
    public static final int RATE_FIELD_NUMBER = 4;
    private com.dh.game.vo.grab.GrabProto.RATETYPE rate_;
    public boolean hasRate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.dh.game.vo.grab.GrabProto.RATETYPE getRate() {
      return rate_;
    }
    
    // repeated .com.dh.game.vo.FinalHero finalHero = 5;
    public static final int FINALHERO_FIELD_NUMBER = 5;
    private java.util.List<com.dh.game.vo.BaseProto.FinalHero> finalHero_;
    public java.util.List<com.dh.game.vo.BaseProto.FinalHero> getFinalHeroList() {
      return finalHero_;
    }
    public java.util.List<? extends com.dh.game.vo.BaseProto.FinalHeroOrBuilder> 
        getFinalHeroOrBuilderList() {
      return finalHero_;
    }
    public int getFinalHeroCount() {
      return finalHero_.size();
    }
    public com.dh.game.vo.BaseProto.FinalHero getFinalHero(int index) {
      return finalHero_.get(index);
    }
    public com.dh.game.vo.BaseProto.FinalHeroOrBuilder getFinalHeroOrBuilder(
        int index) {
      return finalHero_.get(index);
    }
    
    private void initFields() {
      playerId_ = 0;
      name_ = "";
      combat_ = 0;
      rate_ = com.dh.game.vo.grab.GrabProto.RATETYPE.LOW;
      finalHero_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCombat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFinalHeroCount(); i++) {
        if (!getFinalHero(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, combat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, rate_.getNumber());
      }
      for (int i = 0; i < finalHero_.size(); i++) {
        output.writeMessage(5, finalHero_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, combat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, rate_.getNumber());
      }
      for (int i = 0; i < finalHero_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, finalHero_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.grab.GrabProto.GrabRoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.grab.GrabProto.GrabRoleInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.grab.GrabProto.GrabRoleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabRoleInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.grab.GrabProto.internal_static_com_dh_game_vo_grab_GrabRoleInfo_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.grab.GrabProto.GrabRoleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFinalHeroFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        combat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        rate_ = com.dh.game.vo.grab.GrabProto.RATETYPE.LOW;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (finalHeroBuilder_ == null) {
          finalHero_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          finalHeroBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.grab.GrabProto.GrabRoleInfo.getDescriptor();
      }
      
      public com.dh.game.vo.grab.GrabProto.GrabRoleInfo getDefaultInstanceForType() {
        return com.dh.game.vo.grab.GrabProto.GrabRoleInfo.getDefaultInstance();
      }
      
      public com.dh.game.vo.grab.GrabProto.GrabRoleInfo build() {
        com.dh.game.vo.grab.GrabProto.GrabRoleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.grab.GrabProto.GrabRoleInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.grab.GrabProto.GrabRoleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.grab.GrabProto.GrabRoleInfo buildPartial() {
        com.dh.game.vo.grab.GrabProto.GrabRoleInfo result = new com.dh.game.vo.grab.GrabProto.GrabRoleInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.combat_ = combat_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rate_ = rate_;
        if (finalHeroBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            finalHero_ = java.util.Collections.unmodifiableList(finalHero_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.finalHero_ = finalHero_;
        } else {
          result.finalHero_ = finalHeroBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.grab.GrabProto.GrabRoleInfo) {
          return mergeFrom((com.dh.game.vo.grab.GrabProto.GrabRoleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.grab.GrabProto.GrabRoleInfo other) {
        if (other == com.dh.game.vo.grab.GrabProto.GrabRoleInfo.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasCombat()) {
          setCombat(other.getCombat());
        }
        if (other.hasRate()) {
          setRate(other.getRate());
        }
        if (finalHeroBuilder_ == null) {
          if (!other.finalHero_.isEmpty()) {
            if (finalHero_.isEmpty()) {
              finalHero_ = other.finalHero_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureFinalHeroIsMutable();
              finalHero_.addAll(other.finalHero_);
            }
            onChanged();
          }
        } else {
          if (!other.finalHero_.isEmpty()) {
            if (finalHeroBuilder_.isEmpty()) {
              finalHeroBuilder_.dispose();
              finalHeroBuilder_ = null;
              finalHero_ = other.finalHero_;
              bitField0_ = (bitField0_ & ~0x00000010);
              finalHeroBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFinalHeroFieldBuilder() : null;
            } else {
              finalHeroBuilder_.addAllMessages(other.finalHero_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasCombat()) {
          
          return false;
        }
        if (!hasRate()) {
          
          return false;
        }
        for (int i = 0; i < getFinalHeroCount(); i++) {
          if (!getFinalHero(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              combat_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.dh.game.vo.grab.GrabProto.RATETYPE value = com.dh.game.vo.grab.GrabProto.RATETYPE.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                rate_ = value;
              }
              break;
            }
            case 42: {
              com.dh.game.vo.BaseProto.FinalHero.Builder subBuilder = com.dh.game.vo.BaseProto.FinalHero.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFinalHero(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 playerId = 1;
      private int playerId_ ;
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPlayerId() {
        return playerId_;
      }
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // required int32 combat = 3;
      private int combat_ ;
      public boolean hasCombat() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getCombat() {
        return combat_;
      }
      public Builder setCombat(int value) {
        bitField0_ |= 0x00000004;
        combat_ = value;
        onChanged();
        return this;
      }
      public Builder clearCombat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        combat_ = 0;
        onChanged();
        return this;
      }
      
      // required .com.dh.game.vo.grab.RATETYPE rate = 4;
      private com.dh.game.vo.grab.GrabProto.RATETYPE rate_ = com.dh.game.vo.grab.GrabProto.RATETYPE.LOW;
      public boolean hasRate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.dh.game.vo.grab.GrabProto.RATETYPE getRate() {
        return rate_;
      }
      public Builder setRate(com.dh.game.vo.grab.GrabProto.RATETYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        rate_ = value;
        onChanged();
        return this;
      }
      public Builder clearRate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rate_ = com.dh.game.vo.grab.GrabProto.RATETYPE.LOW;
        onChanged();
        return this;
      }
      
      // repeated .com.dh.game.vo.FinalHero finalHero = 5;
      private java.util.List<com.dh.game.vo.BaseProto.FinalHero> finalHero_ =
        java.util.Collections.emptyList();
      private void ensureFinalHeroIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          finalHero_ = new java.util.ArrayList<com.dh.game.vo.BaseProto.FinalHero>(finalHero_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.BaseProto.FinalHero, com.dh.game.vo.BaseProto.FinalHero.Builder, com.dh.game.vo.BaseProto.FinalHeroOrBuilder> finalHeroBuilder_;
      
      public java.util.List<com.dh.game.vo.BaseProto.FinalHero> getFinalHeroList() {
        if (finalHeroBuilder_ == null) {
          return java.util.Collections.unmodifiableList(finalHero_);
        } else {
          return finalHeroBuilder_.getMessageList();
        }
      }
      public int getFinalHeroCount() {
        if (finalHeroBuilder_ == null) {
          return finalHero_.size();
        } else {
          return finalHeroBuilder_.getCount();
        }
      }
      public com.dh.game.vo.BaseProto.FinalHero getFinalHero(int index) {
        if (finalHeroBuilder_ == null) {
          return finalHero_.get(index);
        } else {
          return finalHeroBuilder_.getMessage(index);
        }
      }
      public Builder setFinalHero(
          int index, com.dh.game.vo.BaseProto.FinalHero value) {
        if (finalHeroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFinalHeroIsMutable();
          finalHero_.set(index, value);
          onChanged();
        } else {
          finalHeroBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFinalHero(
          int index, com.dh.game.vo.BaseProto.FinalHero.Builder builderForValue) {
        if (finalHeroBuilder_ == null) {
          ensureFinalHeroIsMutable();
          finalHero_.set(index, builderForValue.build());
          onChanged();
        } else {
          finalHeroBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFinalHero(com.dh.game.vo.BaseProto.FinalHero value) {
        if (finalHeroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFinalHeroIsMutable();
          finalHero_.add(value);
          onChanged();
        } else {
          finalHeroBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFinalHero(
          int index, com.dh.game.vo.BaseProto.FinalHero value) {
        if (finalHeroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFinalHeroIsMutable();
          finalHero_.add(index, value);
          onChanged();
        } else {
          finalHeroBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFinalHero(
          com.dh.game.vo.BaseProto.FinalHero.Builder builderForValue) {
        if (finalHeroBuilder_ == null) {
          ensureFinalHeroIsMutable();
          finalHero_.add(builderForValue.build());
          onChanged();
        } else {
          finalHeroBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFinalHero(
          int index, com.dh.game.vo.BaseProto.FinalHero.Builder builderForValue) {
        if (finalHeroBuilder_ == null) {
          ensureFinalHeroIsMutable();
          finalHero_.add(index, builderForValue.build());
          onChanged();
        } else {
          finalHeroBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFinalHero(
          java.lang.Iterable<? extends com.dh.game.vo.BaseProto.FinalHero> values) {
        if (finalHeroBuilder_ == null) {
          ensureFinalHeroIsMutable();
          super.addAll(values, finalHero_);
          onChanged();
        } else {
          finalHeroBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFinalHero() {
        if (finalHeroBuilder_ == null) {
          finalHero_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          finalHeroBuilder_.clear();
        }
        return this;
      }
      public Builder removeFinalHero(int index) {
        if (finalHeroBuilder_ == null) {
          ensureFinalHeroIsMutable();
          finalHero_.remove(index);
          onChanged();
        } else {
          finalHeroBuilder_.remove(index);
        }
        return this;
      }
      public com.dh.game.vo.BaseProto.FinalHero.Builder getFinalHeroBuilder(
          int index) {
        return getFinalHeroFieldBuilder().getBuilder(index);
      }
      public com.dh.game.vo.BaseProto.FinalHeroOrBuilder getFinalHeroOrBuilder(
          int index) {
        if (finalHeroBuilder_ == null) {
          return finalHero_.get(index);  } else {
          return finalHeroBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.dh.game.vo.BaseProto.FinalHeroOrBuilder> 
           getFinalHeroOrBuilderList() {
        if (finalHeroBuilder_ != null) {
          return finalHeroBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(finalHero_);
        }
      }
      public com.dh.game.vo.BaseProto.FinalHero.Builder addFinalHeroBuilder() {
        return getFinalHeroFieldBuilder().addBuilder(
            com.dh.game.vo.BaseProto.FinalHero.getDefaultInstance());
      }
      public com.dh.game.vo.BaseProto.FinalHero.Builder addFinalHeroBuilder(
          int index) {
        return getFinalHeroFieldBuilder().addBuilder(
            index, com.dh.game.vo.BaseProto.FinalHero.getDefaultInstance());
      }
      public java.util.List<com.dh.game.vo.BaseProto.FinalHero.Builder> 
           getFinalHeroBuilderList() {
        return getFinalHeroFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.BaseProto.FinalHero, com.dh.game.vo.BaseProto.FinalHero.Builder, com.dh.game.vo.BaseProto.FinalHeroOrBuilder> 
          getFinalHeroFieldBuilder() {
        if (finalHeroBuilder_ == null) {
          finalHeroBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dh.game.vo.BaseProto.FinalHero, com.dh.game.vo.BaseProto.FinalHero.Builder, com.dh.game.vo.BaseProto.FinalHeroOrBuilder>(
                  finalHero_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          finalHero_ = null;
        }
        return finalHeroBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.grab.GrabRoleInfo)
    }
    
    static {
      defaultInstance = new GrabRoleInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.grab.GrabRoleInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_grab_GrabListRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_grab_GrabListRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_grab_GrabListResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_grab_GrabListResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_grab_GrabRoleInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_grab_GrabRoleInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036com/proto/shop/GrabProto.proto\022\023com.dh" +
      ".game.vo.grab\032\034com/proto/vo/BaseProto.pr" +
      "oto\"$\n\017GrabListRequest\022\021\n\titemCfgid\030\001 \002(" +
      "\005\"\232\001\n\020GrabListResponse\022\021\n\titemCfgid\030\001 \002(" +
      "\005\0227\n\014grabRoleInfo\030\002 \003(\0132!.com.dh.game.vo" +
      ".grab.GrabRoleInfo\022\017\n\007costpvp\030\003 \002(\005\022\022\n\nr" +
      "emaintime\030\004 \002(\005\022\025\n\rchangeEnempvp\030\005 \002(\005\"\231" +
      "\001\n\014GrabRoleInfo\022\020\n\010playerId\030\001 \002(\005\022\014\n\004nam" +
      "e\030\002 \002(\t\022\016\n\006combat\030\003 \002(\005\022+\n\004rate\030\004 \002(\0162\035." +
      "com.dh.game.vo.grab.RATETYPE\022,\n\tfinalHer",
      "o\030\005 \003(\0132\031.com.dh.game.vo.FinalHero*B\n\010RA" +
      "TETYPE\022\007\n\003LOW\020\001\022\n\n\006MEDIUM\020\002\022\010\n\004HIGH\020\003\022\n\n" +
      "\006HIGHER\020\004\022\013\n\007HIGHEST\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dh_game_vo_grab_GrabListRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dh_game_vo_grab_GrabListRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_grab_GrabListRequest_descriptor,
              new java.lang.String[] { "ItemCfgid", },
              com.dh.game.vo.grab.GrabProto.GrabListRequest.class,
              com.dh.game.vo.grab.GrabProto.GrabListRequest.Builder.class);
          internal_static_com_dh_game_vo_grab_GrabListResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dh_game_vo_grab_GrabListResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_grab_GrabListResponse_descriptor,
              new java.lang.String[] { "ItemCfgid", "GrabRoleInfo", "Costpvp", "Remaintime", "ChangeEnempvp", },
              com.dh.game.vo.grab.GrabProto.GrabListResponse.class,
              com.dh.game.vo.grab.GrabProto.GrabListResponse.Builder.class);
          internal_static_com_dh_game_vo_grab_GrabRoleInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_dh_game_vo_grab_GrabRoleInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_grab_GrabRoleInfo_descriptor,
              new java.lang.String[] { "PlayerId", "Name", "Combat", "Rate", "FinalHero", },
              com.dh.game.vo.grab.GrabProto.GrabRoleInfo.class,
              com.dh.game.vo.grab.GrabProto.GrabRoleInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dh.game.vo.BaseProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
