// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/proto/login/CheckRoleNameProto.proto

package com.dh.game.vo.login;

public final class CheckRoleNameProto {
  private CheckRoleNameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CheckRoleNameRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string rolename = 1;
    boolean hasRolename();
    String getRolename();
  }
  public static final class CheckRoleNameRequest extends
      com.google.protobuf.GeneratedMessage
      implements CheckRoleNameRequestOrBuilder {
    // Use CheckRoleNameRequest.newBuilder() to construct.
    private CheckRoleNameRequest(Builder builder) {
      super(builder);
    }
    private CheckRoleNameRequest(boolean noInit) {}
    
    private static final CheckRoleNameRequest defaultInstance;
    public static CheckRoleNameRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CheckRoleNameRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.login.CheckRoleNameProto.internal_static_com_dh_game_vo_login_CheckRoleNameRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.login.CheckRoleNameProto.internal_static_com_dh_game_vo_login_CheckRoleNameRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string rolename = 1;
    public static final int ROLENAME_FIELD_NUMBER = 1;
    private java.lang.Object rolename_;
    public boolean hasRolename() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRolename() {
      java.lang.Object ref = rolename_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rolename_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRolenameBytes() {
      java.lang.Object ref = rolename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rolename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      rolename_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRolename()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRolenameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRolenameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.login.CheckRoleNameProto.internal_static_com_dh_game_vo_login_CheckRoleNameRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.login.CheckRoleNameProto.internal_static_com_dh_game_vo_login_CheckRoleNameRequest_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        rolename_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest.getDescriptor();
      }
      
      public com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest getDefaultInstanceForType() {
        return com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest.getDefaultInstance();
      }
      
      public com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest build() {
        com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest buildPartial() {
        com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest result = new com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rolename_ = rolename_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest) {
          return mergeFrom((com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest other) {
        if (other == com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest.getDefaultInstance()) return this;
        if (other.hasRolename()) {
          setRolename(other.getRolename());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRolename()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rolename_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string rolename = 1;
      private java.lang.Object rolename_ = "";
      public boolean hasRolename() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRolename() {
        java.lang.Object ref = rolename_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rolename_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRolename(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rolename_ = value;
        onChanged();
        return this;
      }
      public Builder clearRolename() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rolename_ = getDefaultInstance().getRolename();
        onChanged();
        return this;
      }
      void setRolename(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        rolename_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.login.CheckRoleNameRequest)
    }
    
    static {
      defaultInstance = new CheckRoleNameRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.login.CheckRoleNameRequest)
  }
  
  public interface CheckRoleNameResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 result = 1;
    boolean hasResult();
    int getResult();
  }
  public static final class CheckRoleNameResponse extends
      com.google.protobuf.GeneratedMessage
      implements CheckRoleNameResponseOrBuilder {
    // Use CheckRoleNameResponse.newBuilder() to construct.
    private CheckRoleNameResponse(Builder builder) {
      super(builder);
    }
    private CheckRoleNameResponse(boolean noInit) {}
    
    private static final CheckRoleNameResponse defaultInstance;
    public static CheckRoleNameResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CheckRoleNameResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.login.CheckRoleNameProto.internal_static_com_dh_game_vo_login_CheckRoleNameResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.login.CheckRoleNameProto.internal_static_com_dh_game_vo_login_CheckRoleNameResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResult() {
      return result_;
    }
    
    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.login.CheckRoleNameProto.internal_static_com_dh_game_vo_login_CheckRoleNameResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.login.CheckRoleNameProto.internal_static_com_dh_game_vo_login_CheckRoleNameResponse_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse.getDescriptor();
      }
      
      public com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse getDefaultInstanceForType() {
        return com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse.getDefaultInstance();
      }
      
      public com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse build() {
        com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse buildPartial() {
        com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse result = new com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse) {
          return mergeFrom((com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse other) {
        if (other == com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 result = 1;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.login.CheckRoleNameResponse)
    }
    
    static {
      defaultInstance = new CheckRoleNameResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.login.CheckRoleNameResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_login_CheckRoleNameRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_login_CheckRoleNameRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_login_CheckRoleNameResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_login_CheckRoleNameResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com/proto/login/CheckRoleNameProto.pro" +
      "to\022\024com.dh.game.vo.login\"(\n\024CheckRoleNam" +
      "eRequest\022\020\n\010rolename\030\001 \002(\t\"\'\n\025CheckRoleN" +
      "ameResponse\022\016\n\006result\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dh_game_vo_login_CheckRoleNameRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dh_game_vo_login_CheckRoleNameRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_login_CheckRoleNameRequest_descriptor,
              new java.lang.String[] { "Rolename", },
              com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest.class,
              com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameRequest.Builder.class);
          internal_static_com_dh_game_vo_login_CheckRoleNameResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dh_game_vo_login_CheckRoleNameResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_login_CheckRoleNameResponse_descriptor,
              new java.lang.String[] { "Result", },
              com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse.class,
              com.dh.game.vo.login.CheckRoleNameProto.CheckRoleNameResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
