// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/proto/server/ServerProto.proto

package com.dh.game.vo.server;

public final class ServerProto {
  private ServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum SERVERTYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    GATE(0, 1),
    BATTLE(1, 2),
    ;
    
    public static final int GATE_VALUE = 1;
    public static final int BATTLE_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static SERVERTYPE valueOf(int value) {
      switch (value) {
        case 1: return GATE;
        case 2: return BATTLE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<SERVERTYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SERVERTYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SERVERTYPE>() {
            public SERVERTYPE findValueByNumber(int number) {
              return SERVERTYPE.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.dh.game.vo.server.ServerProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final SERVERTYPE[] VALUES = {
      GATE, BATTLE, 
    };
    
    public static SERVERTYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private SERVERTYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.dh.game.vo.server.SERVERTYPE)
  }
  
  public interface ServerRegisterRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 serverId = 1;
    boolean hasServerId();
    int getServerId();
    
    // required .com.dh.game.vo.server.SERVERTYPE serverType = 2;
    boolean hasServerType();
    com.dh.game.vo.server.ServerProto.SERVERTYPE getServerType();
  }
  public static final class ServerRegisterRequest extends
      com.google.protobuf.GeneratedMessage
      implements ServerRegisterRequestOrBuilder {
    // Use ServerRegisterRequest.newBuilder() to construct.
    private ServerRegisterRequest(Builder builder) {
      super(builder);
    }
    private ServerRegisterRequest(boolean noInit) {}
    
    private static final ServerRegisterRequest defaultInstance;
    public static ServerRegisterRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServerRegisterRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.server.ServerProto.internal_static_com_dh_game_vo_server_ServerRegisterRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.server.ServerProto.internal_static_com_dh_game_vo_server_ServerRegisterRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 serverId = 1;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_;
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getServerId() {
      return serverId_;
    }
    
    // required .com.dh.game.vo.server.SERVERTYPE serverType = 2;
    public static final int SERVERTYPE_FIELD_NUMBER = 2;
    private com.dh.game.vo.server.ServerProto.SERVERTYPE serverType_;
    public boolean hasServerType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.dh.game.vo.server.ServerProto.SERVERTYPE getServerType() {
      return serverType_;
    }
    
    private void initFields() {
      serverId_ = 0;
      serverType_ = com.dh.game.vo.server.ServerProto.SERVERTYPE.GATE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, serverType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, serverType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.server.ServerProto.ServerRegisterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.server.ServerProto.ServerRegisterRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.server.ServerProto.ServerRegisterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.server.ServerProto.internal_static_com_dh_game_vo_server_ServerRegisterRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.server.ServerProto.internal_static_com_dh_game_vo_server_ServerRegisterRequest_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.server.ServerProto.ServerRegisterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverType_ = com.dh.game.vo.server.ServerProto.SERVERTYPE.GATE;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.server.ServerProto.ServerRegisterRequest.getDescriptor();
      }
      
      public com.dh.game.vo.server.ServerProto.ServerRegisterRequest getDefaultInstanceForType() {
        return com.dh.game.vo.server.ServerProto.ServerRegisterRequest.getDefaultInstance();
      }
      
      public com.dh.game.vo.server.ServerProto.ServerRegisterRequest build() {
        com.dh.game.vo.server.ServerProto.ServerRegisterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.server.ServerProto.ServerRegisterRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.server.ServerProto.ServerRegisterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.server.ServerProto.ServerRegisterRequest buildPartial() {
        com.dh.game.vo.server.ServerProto.ServerRegisterRequest result = new com.dh.game.vo.server.ServerProto.ServerRegisterRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverType_ = serverType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.server.ServerProto.ServerRegisterRequest) {
          return mergeFrom((com.dh.game.vo.server.ServerProto.ServerRegisterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.server.ServerProto.ServerRegisterRequest other) {
        if (other == com.dh.game.vo.server.ServerProto.ServerRegisterRequest.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasServerType()) {
          setServerType(other.getServerType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasServerId()) {
          
          return false;
        }
        if (!hasServerType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.dh.game.vo.server.ServerProto.SERVERTYPE value = com.dh.game.vo.server.ServerProto.SERVERTYPE.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                serverType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 serverId = 1;
      private int serverId_ ;
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getServerId() {
        return serverId_;
      }
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }
      
      // required .com.dh.game.vo.server.SERVERTYPE serverType = 2;
      private com.dh.game.vo.server.ServerProto.SERVERTYPE serverType_ = com.dh.game.vo.server.ServerProto.SERVERTYPE.GATE;
      public boolean hasServerType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.dh.game.vo.server.ServerProto.SERVERTYPE getServerType() {
        return serverType_;
      }
      public Builder setServerType(com.dh.game.vo.server.ServerProto.SERVERTYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        serverType_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverType_ = com.dh.game.vo.server.ServerProto.SERVERTYPE.GATE;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.server.ServerRegisterRequest)
    }
    
    static {
      defaultInstance = new ServerRegisterRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.server.ServerRegisterRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_server_ServerRegisterRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_server_ServerRegisterRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"com/proto/server/ServerProto.proto\022\025co" +
      "m.dh.game.vo.server\"`\n\025ServerRegisterReq" +
      "uest\022\020\n\010serverId\030\001 \002(\005\0225\n\nserverType\030\002 \002" +
      "(\0162!.com.dh.game.vo.server.SERVERTYPE*\"\n" +
      "\nSERVERTYPE\022\010\n\004GATE\020\001\022\n\n\006BATTLE\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dh_game_vo_server_ServerRegisterRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dh_game_vo_server_ServerRegisterRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_server_ServerRegisterRequest_descriptor,
              new java.lang.String[] { "ServerId", "ServerType", },
              com.dh.game.vo.server.ServerProto.ServerRegisterRequest.class,
              com.dh.game.vo.server.ServerProto.ServerRegisterRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
