// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/proto/task/PlayerTask.proto

package com.dh.game.vo.task;

public final class PlayerTask {
  private PlayerTask() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TaskInfoResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.dh.game.vo.MyTask myTask = 1;
    java.util.List<com.dh.game.vo.BaseProto.MyTask> 
        getMyTaskList();
    com.dh.game.vo.BaseProto.MyTask getMyTask(int index);
    int getMyTaskCount();
    java.util.List<? extends com.dh.game.vo.BaseProto.MyTaskOrBuilder> 
        getMyTaskOrBuilderList();
    com.dh.game.vo.BaseProto.MyTaskOrBuilder getMyTaskOrBuilder(
        int index);
  }
  public static final class TaskInfoResponse extends
      com.google.protobuf.GeneratedMessage
      implements TaskInfoResponseOrBuilder {
    // Use TaskInfoResponse.newBuilder() to construct.
    private TaskInfoResponse(Builder builder) {
      super(builder);
    }
    private TaskInfoResponse(boolean noInit) {}
    
    private static final TaskInfoResponse defaultInstance;
    public static TaskInfoResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public TaskInfoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.task.PlayerTask.internal_static_com_dh_game_vo_task_TaskInfoResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.task.PlayerTask.internal_static_com_dh_game_vo_task_TaskInfoResponse_fieldAccessorTable;
    }
    
    // repeated .com.dh.game.vo.MyTask myTask = 1;
    public static final int MYTASK_FIELD_NUMBER = 1;
    private java.util.List<com.dh.game.vo.BaseProto.MyTask> myTask_;
    public java.util.List<com.dh.game.vo.BaseProto.MyTask> getMyTaskList() {
      return myTask_;
    }
    public java.util.List<? extends com.dh.game.vo.BaseProto.MyTaskOrBuilder> 
        getMyTaskOrBuilderList() {
      return myTask_;
    }
    public int getMyTaskCount() {
      return myTask_.size();
    }
    public com.dh.game.vo.BaseProto.MyTask getMyTask(int index) {
      return myTask_.get(index);
    }
    public com.dh.game.vo.BaseProto.MyTaskOrBuilder getMyTaskOrBuilder(
        int index) {
      return myTask_.get(index);
    }
    
    private void initFields() {
      myTask_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getMyTaskCount(); i++) {
        if (!getMyTask(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < myTask_.size(); i++) {
        output.writeMessage(1, myTask_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < myTask_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, myTask_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.TaskInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.task.PlayerTask.TaskInfoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.task.PlayerTask.TaskInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.task.PlayerTask.internal_static_com_dh_game_vo_task_TaskInfoResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.task.PlayerTask.internal_static_com_dh_game_vo_task_TaskInfoResponse_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.task.PlayerTask.TaskInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMyTaskFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (myTaskBuilder_ == null) {
          myTask_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          myTaskBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.task.PlayerTask.TaskInfoResponse.getDescriptor();
      }
      
      public com.dh.game.vo.task.PlayerTask.TaskInfoResponse getDefaultInstanceForType() {
        return com.dh.game.vo.task.PlayerTask.TaskInfoResponse.getDefaultInstance();
      }
      
      public com.dh.game.vo.task.PlayerTask.TaskInfoResponse build() {
        com.dh.game.vo.task.PlayerTask.TaskInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.task.PlayerTask.TaskInfoResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.task.PlayerTask.TaskInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.task.PlayerTask.TaskInfoResponse buildPartial() {
        com.dh.game.vo.task.PlayerTask.TaskInfoResponse result = new com.dh.game.vo.task.PlayerTask.TaskInfoResponse(this);
        int from_bitField0_ = bitField0_;
        if (myTaskBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            myTask_ = java.util.Collections.unmodifiableList(myTask_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.myTask_ = myTask_;
        } else {
          result.myTask_ = myTaskBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.task.PlayerTask.TaskInfoResponse) {
          return mergeFrom((com.dh.game.vo.task.PlayerTask.TaskInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.task.PlayerTask.TaskInfoResponse other) {
        if (other == com.dh.game.vo.task.PlayerTask.TaskInfoResponse.getDefaultInstance()) return this;
        if (myTaskBuilder_ == null) {
          if (!other.myTask_.isEmpty()) {
            if (myTask_.isEmpty()) {
              myTask_ = other.myTask_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMyTaskIsMutable();
              myTask_.addAll(other.myTask_);
            }
            onChanged();
          }
        } else {
          if (!other.myTask_.isEmpty()) {
            if (myTaskBuilder_.isEmpty()) {
              myTaskBuilder_.dispose();
              myTaskBuilder_ = null;
              myTask_ = other.myTask_;
              bitField0_ = (bitField0_ & ~0x00000001);
              myTaskBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMyTaskFieldBuilder() : null;
            } else {
              myTaskBuilder_.addAllMessages(other.myTask_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getMyTaskCount(); i++) {
          if (!getMyTask(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.dh.game.vo.BaseProto.MyTask.Builder subBuilder = com.dh.game.vo.BaseProto.MyTask.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMyTask(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.dh.game.vo.MyTask myTask = 1;
      private java.util.List<com.dh.game.vo.BaseProto.MyTask> myTask_ =
        java.util.Collections.emptyList();
      private void ensureMyTaskIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          myTask_ = new java.util.ArrayList<com.dh.game.vo.BaseProto.MyTask>(myTask_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.BaseProto.MyTask, com.dh.game.vo.BaseProto.MyTask.Builder, com.dh.game.vo.BaseProto.MyTaskOrBuilder> myTaskBuilder_;
      
      public java.util.List<com.dh.game.vo.BaseProto.MyTask> getMyTaskList() {
        if (myTaskBuilder_ == null) {
          return java.util.Collections.unmodifiableList(myTask_);
        } else {
          return myTaskBuilder_.getMessageList();
        }
      }
      public int getMyTaskCount() {
        if (myTaskBuilder_ == null) {
          return myTask_.size();
        } else {
          return myTaskBuilder_.getCount();
        }
      }
      public com.dh.game.vo.BaseProto.MyTask getMyTask(int index) {
        if (myTaskBuilder_ == null) {
          return myTask_.get(index);
        } else {
          return myTaskBuilder_.getMessage(index);
        }
      }
      public Builder setMyTask(
          int index, com.dh.game.vo.BaseProto.MyTask value) {
        if (myTaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMyTaskIsMutable();
          myTask_.set(index, value);
          onChanged();
        } else {
          myTaskBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMyTask(
          int index, com.dh.game.vo.BaseProto.MyTask.Builder builderForValue) {
        if (myTaskBuilder_ == null) {
          ensureMyTaskIsMutable();
          myTask_.set(index, builderForValue.build());
          onChanged();
        } else {
          myTaskBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMyTask(com.dh.game.vo.BaseProto.MyTask value) {
        if (myTaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMyTaskIsMutable();
          myTask_.add(value);
          onChanged();
        } else {
          myTaskBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMyTask(
          int index, com.dh.game.vo.BaseProto.MyTask value) {
        if (myTaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMyTaskIsMutable();
          myTask_.add(index, value);
          onChanged();
        } else {
          myTaskBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMyTask(
          com.dh.game.vo.BaseProto.MyTask.Builder builderForValue) {
        if (myTaskBuilder_ == null) {
          ensureMyTaskIsMutable();
          myTask_.add(builderForValue.build());
          onChanged();
        } else {
          myTaskBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMyTask(
          int index, com.dh.game.vo.BaseProto.MyTask.Builder builderForValue) {
        if (myTaskBuilder_ == null) {
          ensureMyTaskIsMutable();
          myTask_.add(index, builderForValue.build());
          onChanged();
        } else {
          myTaskBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMyTask(
          java.lang.Iterable<? extends com.dh.game.vo.BaseProto.MyTask> values) {
        if (myTaskBuilder_ == null) {
          ensureMyTaskIsMutable();
          super.addAll(values, myTask_);
          onChanged();
        } else {
          myTaskBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMyTask() {
        if (myTaskBuilder_ == null) {
          myTask_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          myTaskBuilder_.clear();
        }
        return this;
      }
      public Builder removeMyTask(int index) {
        if (myTaskBuilder_ == null) {
          ensureMyTaskIsMutable();
          myTask_.remove(index);
          onChanged();
        } else {
          myTaskBuilder_.remove(index);
        }
        return this;
      }
      public com.dh.game.vo.BaseProto.MyTask.Builder getMyTaskBuilder(
          int index) {
        return getMyTaskFieldBuilder().getBuilder(index);
      }
      public com.dh.game.vo.BaseProto.MyTaskOrBuilder getMyTaskOrBuilder(
          int index) {
        if (myTaskBuilder_ == null) {
          return myTask_.get(index);  } else {
          return myTaskBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.dh.game.vo.BaseProto.MyTaskOrBuilder> 
           getMyTaskOrBuilderList() {
        if (myTaskBuilder_ != null) {
          return myTaskBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(myTask_);
        }
      }
      public com.dh.game.vo.BaseProto.MyTask.Builder addMyTaskBuilder() {
        return getMyTaskFieldBuilder().addBuilder(
            com.dh.game.vo.BaseProto.MyTask.getDefaultInstance());
      }
      public com.dh.game.vo.BaseProto.MyTask.Builder addMyTaskBuilder(
          int index) {
        return getMyTaskFieldBuilder().addBuilder(
            index, com.dh.game.vo.BaseProto.MyTask.getDefaultInstance());
      }
      public java.util.List<com.dh.game.vo.BaseProto.MyTask.Builder> 
           getMyTaskBuilderList() {
        return getMyTaskFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.BaseProto.MyTask, com.dh.game.vo.BaseProto.MyTask.Builder, com.dh.game.vo.BaseProto.MyTaskOrBuilder> 
          getMyTaskFieldBuilder() {
        if (myTaskBuilder_ == null) {
          myTaskBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dh.game.vo.BaseProto.MyTask, com.dh.game.vo.BaseProto.MyTask.Builder, com.dh.game.vo.BaseProto.MyTaskOrBuilder>(
                  myTask_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          myTask_ = null;
        }
        return myTaskBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.task.TaskInfoResponse)
    }
    
    static {
      defaultInstance = new TaskInfoResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.task.TaskInfoResponse)
  }
  
  public interface ReceiveTaskRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 taskId = 1;
    boolean hasTaskId();
    int getTaskId();
  }
  public static final class ReceiveTaskRequest extends
      com.google.protobuf.GeneratedMessage
      implements ReceiveTaskRequestOrBuilder {
    // Use ReceiveTaskRequest.newBuilder() to construct.
    private ReceiveTaskRequest(Builder builder) {
      super(builder);
    }
    private ReceiveTaskRequest(boolean noInit) {}
    
    private static final ReceiveTaskRequest defaultInstance;
    public static ReceiveTaskRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ReceiveTaskRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.task.PlayerTask.internal_static_com_dh_game_vo_task_ReceiveTaskRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.task.PlayerTask.internal_static_com_dh_game_vo_task_ReceiveTaskRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 taskId = 1;
    public static final int TASKID_FIELD_NUMBER = 1;
    private int taskId_;
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTaskId() {
      return taskId_;
    }
    
    private void initFields() {
      taskId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, taskId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, taskId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.task.PlayerTask.ReceiveTaskRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.task.PlayerTask.internal_static_com_dh_game_vo_task_ReceiveTaskRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.task.PlayerTask.internal_static_com_dh_game_vo_task_ReceiveTaskRequest_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest.getDescriptor();
      }
      
      public com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest getDefaultInstanceForType() {
        return com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest.getDefaultInstance();
      }
      
      public com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest build() {
        com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest buildPartial() {
        com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest result = new com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskId_ = taskId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest) {
          return mergeFrom((com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest other) {
        if (other == com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest.getDefaultInstance()) return this;
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTaskId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              taskId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 taskId = 1;
      private int taskId_ ;
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTaskId() {
        return taskId_;
      }
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000001;
        taskId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.task.ReceiveTaskRequest)
    }
    
    static {
      defaultInstance = new ReceiveTaskRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.task.ReceiveTaskRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_task_TaskInfoResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_task_TaskInfoResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_task_ReceiveTaskRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_task_ReceiveTaskRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037com/proto/task/PlayerTask.proto\022\023com.d" +
      "h.game.vo.task\032\034com/proto/vo/BaseProto.p" +
      "roto\":\n\020TaskInfoResponse\022&\n\006myTask\030\001 \003(\013" +
      "2\026.com.dh.game.vo.MyTask\"$\n\022ReceiveTaskR" +
      "equest\022\016\n\006taskId\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dh_game_vo_task_TaskInfoResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dh_game_vo_task_TaskInfoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_task_TaskInfoResponse_descriptor,
              new java.lang.String[] { "MyTask", },
              com.dh.game.vo.task.PlayerTask.TaskInfoResponse.class,
              com.dh.game.vo.task.PlayerTask.TaskInfoResponse.Builder.class);
          internal_static_com_dh_game_vo_task_ReceiveTaskRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dh_game_vo_task_ReceiveTaskRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_task_ReceiveTaskRequest_descriptor,
              new java.lang.String[] { "TaskId", },
              com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest.class,
              com.dh.game.vo.task.PlayerTask.ReceiveTaskRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dh.game.vo.BaseProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
