// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/proto/common/TestProto.proto

package com.dh.game.vo.common;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface testRepeatRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.dh.game.vo.common.TestRepeatInfo testRepeatInfo = 1;
    java.util.List<com.dh.game.vo.common.TestProto.TestRepeatInfo> 
        getTestRepeatInfoList();
    com.dh.game.vo.common.TestProto.TestRepeatInfo getTestRepeatInfo(int index);
    int getTestRepeatInfoCount();
    java.util.List<? extends com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder> 
        getTestRepeatInfoOrBuilderList();
    com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder getTestRepeatInfoOrBuilder(
        int index);
    
    // repeated .com.dh.game.vo.common.TestRepeatedInfo2 testRepeatedInfo2 = 2;
    java.util.List<com.dh.game.vo.common.TestProto.TestRepeatedInfo2> 
        getTestRepeatedInfo2List();
    com.dh.game.vo.common.TestProto.TestRepeatedInfo2 getTestRepeatedInfo2(int index);
    int getTestRepeatedInfo2Count();
    java.util.List<? extends com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder> 
        getTestRepeatedInfo2OrBuilderList();
    com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder getTestRepeatedInfo2OrBuilder(
        int index);
  }
  public static final class testRepeatResp extends
      com.google.protobuf.GeneratedMessage
      implements testRepeatRespOrBuilder {
    // Use testRepeatResp.newBuilder() to construct.
    private testRepeatResp(Builder builder) {
      super(builder);
    }
    private testRepeatResp(boolean noInit) {}
    
    private static final testRepeatResp defaultInstance;
    public static testRepeatResp getDefaultInstance() {
      return defaultInstance;
    }
    
    public testRepeatResp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_testRepeatResp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_testRepeatResp_fieldAccessorTable;
    }
    
    // repeated .com.dh.game.vo.common.TestRepeatInfo testRepeatInfo = 1;
    public static final int TESTREPEATINFO_FIELD_NUMBER = 1;
    private java.util.List<com.dh.game.vo.common.TestProto.TestRepeatInfo> testRepeatInfo_;
    public java.util.List<com.dh.game.vo.common.TestProto.TestRepeatInfo> getTestRepeatInfoList() {
      return testRepeatInfo_;
    }
    public java.util.List<? extends com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder> 
        getTestRepeatInfoOrBuilderList() {
      return testRepeatInfo_;
    }
    public int getTestRepeatInfoCount() {
      return testRepeatInfo_.size();
    }
    public com.dh.game.vo.common.TestProto.TestRepeatInfo getTestRepeatInfo(int index) {
      return testRepeatInfo_.get(index);
    }
    public com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder getTestRepeatInfoOrBuilder(
        int index) {
      return testRepeatInfo_.get(index);
    }
    
    // repeated .com.dh.game.vo.common.TestRepeatedInfo2 testRepeatedInfo2 = 2;
    public static final int TESTREPEATEDINFO2_FIELD_NUMBER = 2;
    private java.util.List<com.dh.game.vo.common.TestProto.TestRepeatedInfo2> testRepeatedInfo2_;
    public java.util.List<com.dh.game.vo.common.TestProto.TestRepeatedInfo2> getTestRepeatedInfo2List() {
      return testRepeatedInfo2_;
    }
    public java.util.List<? extends com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder> 
        getTestRepeatedInfo2OrBuilderList() {
      return testRepeatedInfo2_;
    }
    public int getTestRepeatedInfo2Count() {
      return testRepeatedInfo2_.size();
    }
    public com.dh.game.vo.common.TestProto.TestRepeatedInfo2 getTestRepeatedInfo2(int index) {
      return testRepeatedInfo2_.get(index);
    }
    public com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder getTestRepeatedInfo2OrBuilder(
        int index) {
      return testRepeatedInfo2_.get(index);
    }
    
    private void initFields() {
      testRepeatInfo_ = java.util.Collections.emptyList();
      testRepeatedInfo2_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getTestRepeatInfoCount(); i++) {
        if (!getTestRepeatInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getTestRepeatedInfo2Count(); i++) {
        if (!getTestRepeatedInfo2(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < testRepeatInfo_.size(); i++) {
        output.writeMessage(1, testRepeatInfo_.get(i));
      }
      for (int i = 0; i < testRepeatedInfo2_.size(); i++) {
        output.writeMessage(2, testRepeatedInfo2_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < testRepeatInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, testRepeatInfo_.get(i));
      }
      for (int i = 0; i < testRepeatedInfo2_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, testRepeatedInfo2_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.testRepeatResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.common.TestProto.testRepeatResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.common.TestProto.testRepeatRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_testRepeatResp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_testRepeatResp_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.common.TestProto.testRepeatResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTestRepeatInfoFieldBuilder();
          getTestRepeatedInfo2FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (testRepeatInfoBuilder_ == null) {
          testRepeatInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          testRepeatInfoBuilder_.clear();
        }
        if (testRepeatedInfo2Builder_ == null) {
          testRepeatedInfo2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          testRepeatedInfo2Builder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.common.TestProto.testRepeatResp.getDescriptor();
      }
      
      public com.dh.game.vo.common.TestProto.testRepeatResp getDefaultInstanceForType() {
        return com.dh.game.vo.common.TestProto.testRepeatResp.getDefaultInstance();
      }
      
      public com.dh.game.vo.common.TestProto.testRepeatResp build() {
        com.dh.game.vo.common.TestProto.testRepeatResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.common.TestProto.testRepeatResp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.common.TestProto.testRepeatResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.common.TestProto.testRepeatResp buildPartial() {
        com.dh.game.vo.common.TestProto.testRepeatResp result = new com.dh.game.vo.common.TestProto.testRepeatResp(this);
        int from_bitField0_ = bitField0_;
        if (testRepeatInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            testRepeatInfo_ = java.util.Collections.unmodifiableList(testRepeatInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.testRepeatInfo_ = testRepeatInfo_;
        } else {
          result.testRepeatInfo_ = testRepeatInfoBuilder_.build();
        }
        if (testRepeatedInfo2Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            testRepeatedInfo2_ = java.util.Collections.unmodifiableList(testRepeatedInfo2_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.testRepeatedInfo2_ = testRepeatedInfo2_;
        } else {
          result.testRepeatedInfo2_ = testRepeatedInfo2Builder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.common.TestProto.testRepeatResp) {
          return mergeFrom((com.dh.game.vo.common.TestProto.testRepeatResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.common.TestProto.testRepeatResp other) {
        if (other == com.dh.game.vo.common.TestProto.testRepeatResp.getDefaultInstance()) return this;
        if (testRepeatInfoBuilder_ == null) {
          if (!other.testRepeatInfo_.isEmpty()) {
            if (testRepeatInfo_.isEmpty()) {
              testRepeatInfo_ = other.testRepeatInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTestRepeatInfoIsMutable();
              testRepeatInfo_.addAll(other.testRepeatInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.testRepeatInfo_.isEmpty()) {
            if (testRepeatInfoBuilder_.isEmpty()) {
              testRepeatInfoBuilder_.dispose();
              testRepeatInfoBuilder_ = null;
              testRepeatInfo_ = other.testRepeatInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              testRepeatInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTestRepeatInfoFieldBuilder() : null;
            } else {
              testRepeatInfoBuilder_.addAllMessages(other.testRepeatInfo_);
            }
          }
        }
        if (testRepeatedInfo2Builder_ == null) {
          if (!other.testRepeatedInfo2_.isEmpty()) {
            if (testRepeatedInfo2_.isEmpty()) {
              testRepeatedInfo2_ = other.testRepeatedInfo2_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTestRepeatedInfo2IsMutable();
              testRepeatedInfo2_.addAll(other.testRepeatedInfo2_);
            }
            onChanged();
          }
        } else {
          if (!other.testRepeatedInfo2_.isEmpty()) {
            if (testRepeatedInfo2Builder_.isEmpty()) {
              testRepeatedInfo2Builder_.dispose();
              testRepeatedInfo2Builder_ = null;
              testRepeatedInfo2_ = other.testRepeatedInfo2_;
              bitField0_ = (bitField0_ & ~0x00000002);
              testRepeatedInfo2Builder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTestRepeatedInfo2FieldBuilder() : null;
            } else {
              testRepeatedInfo2Builder_.addAllMessages(other.testRepeatedInfo2_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getTestRepeatInfoCount(); i++) {
          if (!getTestRepeatInfo(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getTestRepeatedInfo2Count(); i++) {
          if (!getTestRepeatedInfo2(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder subBuilder = com.dh.game.vo.common.TestProto.TestRepeatInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTestRepeatInfo(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder subBuilder = com.dh.game.vo.common.TestProto.TestRepeatedInfo2.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTestRepeatedInfo2(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.dh.game.vo.common.TestRepeatInfo testRepeatInfo = 1;
      private java.util.List<com.dh.game.vo.common.TestProto.TestRepeatInfo> testRepeatInfo_ =
        java.util.Collections.emptyList();
      private void ensureTestRepeatInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          testRepeatInfo_ = new java.util.ArrayList<com.dh.game.vo.common.TestProto.TestRepeatInfo>(testRepeatInfo_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.common.TestProto.TestRepeatInfo, com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder, com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder> testRepeatInfoBuilder_;
      
      public java.util.List<com.dh.game.vo.common.TestProto.TestRepeatInfo> getTestRepeatInfoList() {
        if (testRepeatInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(testRepeatInfo_);
        } else {
          return testRepeatInfoBuilder_.getMessageList();
        }
      }
      public int getTestRepeatInfoCount() {
        if (testRepeatInfoBuilder_ == null) {
          return testRepeatInfo_.size();
        } else {
          return testRepeatInfoBuilder_.getCount();
        }
      }
      public com.dh.game.vo.common.TestProto.TestRepeatInfo getTestRepeatInfo(int index) {
        if (testRepeatInfoBuilder_ == null) {
          return testRepeatInfo_.get(index);
        } else {
          return testRepeatInfoBuilder_.getMessage(index);
        }
      }
      public Builder setTestRepeatInfo(
          int index, com.dh.game.vo.common.TestProto.TestRepeatInfo value) {
        if (testRepeatInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTestRepeatInfoIsMutable();
          testRepeatInfo_.set(index, value);
          onChanged();
        } else {
          testRepeatInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTestRepeatInfo(
          int index, com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder builderForValue) {
        if (testRepeatInfoBuilder_ == null) {
          ensureTestRepeatInfoIsMutable();
          testRepeatInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          testRepeatInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTestRepeatInfo(com.dh.game.vo.common.TestProto.TestRepeatInfo value) {
        if (testRepeatInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTestRepeatInfoIsMutable();
          testRepeatInfo_.add(value);
          onChanged();
        } else {
          testRepeatInfoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTestRepeatInfo(
          int index, com.dh.game.vo.common.TestProto.TestRepeatInfo value) {
        if (testRepeatInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTestRepeatInfoIsMutable();
          testRepeatInfo_.add(index, value);
          onChanged();
        } else {
          testRepeatInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTestRepeatInfo(
          com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder builderForValue) {
        if (testRepeatInfoBuilder_ == null) {
          ensureTestRepeatInfoIsMutable();
          testRepeatInfo_.add(builderForValue.build());
          onChanged();
        } else {
          testRepeatInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTestRepeatInfo(
          int index, com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder builderForValue) {
        if (testRepeatInfoBuilder_ == null) {
          ensureTestRepeatInfoIsMutable();
          testRepeatInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          testRepeatInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTestRepeatInfo(
          java.lang.Iterable<? extends com.dh.game.vo.common.TestProto.TestRepeatInfo> values) {
        if (testRepeatInfoBuilder_ == null) {
          ensureTestRepeatInfoIsMutable();
          super.addAll(values, testRepeatInfo_);
          onChanged();
        } else {
          testRepeatInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTestRepeatInfo() {
        if (testRepeatInfoBuilder_ == null) {
          testRepeatInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          testRepeatInfoBuilder_.clear();
        }
        return this;
      }
      public Builder removeTestRepeatInfo(int index) {
        if (testRepeatInfoBuilder_ == null) {
          ensureTestRepeatInfoIsMutable();
          testRepeatInfo_.remove(index);
          onChanged();
        } else {
          testRepeatInfoBuilder_.remove(index);
        }
        return this;
      }
      public com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder getTestRepeatInfoBuilder(
          int index) {
        return getTestRepeatInfoFieldBuilder().getBuilder(index);
      }
      public com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder getTestRepeatInfoOrBuilder(
          int index) {
        if (testRepeatInfoBuilder_ == null) {
          return testRepeatInfo_.get(index);  } else {
          return testRepeatInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder> 
           getTestRepeatInfoOrBuilderList() {
        if (testRepeatInfoBuilder_ != null) {
          return testRepeatInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(testRepeatInfo_);
        }
      }
      public com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder addTestRepeatInfoBuilder() {
        return getTestRepeatInfoFieldBuilder().addBuilder(
            com.dh.game.vo.common.TestProto.TestRepeatInfo.getDefaultInstance());
      }
      public com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder addTestRepeatInfoBuilder(
          int index) {
        return getTestRepeatInfoFieldBuilder().addBuilder(
            index, com.dh.game.vo.common.TestProto.TestRepeatInfo.getDefaultInstance());
      }
      public java.util.List<com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder> 
           getTestRepeatInfoBuilderList() {
        return getTestRepeatInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.common.TestProto.TestRepeatInfo, com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder, com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder> 
          getTestRepeatInfoFieldBuilder() {
        if (testRepeatInfoBuilder_ == null) {
          testRepeatInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dh.game.vo.common.TestProto.TestRepeatInfo, com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder, com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder>(
                  testRepeatInfo_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          testRepeatInfo_ = null;
        }
        return testRepeatInfoBuilder_;
      }
      
      // repeated .com.dh.game.vo.common.TestRepeatedInfo2 testRepeatedInfo2 = 2;
      private java.util.List<com.dh.game.vo.common.TestProto.TestRepeatedInfo2> testRepeatedInfo2_ =
        java.util.Collections.emptyList();
      private void ensureTestRepeatedInfo2IsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          testRepeatedInfo2_ = new java.util.ArrayList<com.dh.game.vo.common.TestProto.TestRepeatedInfo2>(testRepeatedInfo2_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.common.TestProto.TestRepeatedInfo2, com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder, com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder> testRepeatedInfo2Builder_;
      
      public java.util.List<com.dh.game.vo.common.TestProto.TestRepeatedInfo2> getTestRepeatedInfo2List() {
        if (testRepeatedInfo2Builder_ == null) {
          return java.util.Collections.unmodifiableList(testRepeatedInfo2_);
        } else {
          return testRepeatedInfo2Builder_.getMessageList();
        }
      }
      public int getTestRepeatedInfo2Count() {
        if (testRepeatedInfo2Builder_ == null) {
          return testRepeatedInfo2_.size();
        } else {
          return testRepeatedInfo2Builder_.getCount();
        }
      }
      public com.dh.game.vo.common.TestProto.TestRepeatedInfo2 getTestRepeatedInfo2(int index) {
        if (testRepeatedInfo2Builder_ == null) {
          return testRepeatedInfo2_.get(index);
        } else {
          return testRepeatedInfo2Builder_.getMessage(index);
        }
      }
      public Builder setTestRepeatedInfo2(
          int index, com.dh.game.vo.common.TestProto.TestRepeatedInfo2 value) {
        if (testRepeatedInfo2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTestRepeatedInfo2IsMutable();
          testRepeatedInfo2_.set(index, value);
          onChanged();
        } else {
          testRepeatedInfo2Builder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTestRepeatedInfo2(
          int index, com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder builderForValue) {
        if (testRepeatedInfo2Builder_ == null) {
          ensureTestRepeatedInfo2IsMutable();
          testRepeatedInfo2_.set(index, builderForValue.build());
          onChanged();
        } else {
          testRepeatedInfo2Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTestRepeatedInfo2(com.dh.game.vo.common.TestProto.TestRepeatedInfo2 value) {
        if (testRepeatedInfo2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTestRepeatedInfo2IsMutable();
          testRepeatedInfo2_.add(value);
          onChanged();
        } else {
          testRepeatedInfo2Builder_.addMessage(value);
        }
        return this;
      }
      public Builder addTestRepeatedInfo2(
          int index, com.dh.game.vo.common.TestProto.TestRepeatedInfo2 value) {
        if (testRepeatedInfo2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTestRepeatedInfo2IsMutable();
          testRepeatedInfo2_.add(index, value);
          onChanged();
        } else {
          testRepeatedInfo2Builder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTestRepeatedInfo2(
          com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder builderForValue) {
        if (testRepeatedInfo2Builder_ == null) {
          ensureTestRepeatedInfo2IsMutable();
          testRepeatedInfo2_.add(builderForValue.build());
          onChanged();
        } else {
          testRepeatedInfo2Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTestRepeatedInfo2(
          int index, com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder builderForValue) {
        if (testRepeatedInfo2Builder_ == null) {
          ensureTestRepeatedInfo2IsMutable();
          testRepeatedInfo2_.add(index, builderForValue.build());
          onChanged();
        } else {
          testRepeatedInfo2Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTestRepeatedInfo2(
          java.lang.Iterable<? extends com.dh.game.vo.common.TestProto.TestRepeatedInfo2> values) {
        if (testRepeatedInfo2Builder_ == null) {
          ensureTestRepeatedInfo2IsMutable();
          super.addAll(values, testRepeatedInfo2_);
          onChanged();
        } else {
          testRepeatedInfo2Builder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTestRepeatedInfo2() {
        if (testRepeatedInfo2Builder_ == null) {
          testRepeatedInfo2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          testRepeatedInfo2Builder_.clear();
        }
        return this;
      }
      public Builder removeTestRepeatedInfo2(int index) {
        if (testRepeatedInfo2Builder_ == null) {
          ensureTestRepeatedInfo2IsMutable();
          testRepeatedInfo2_.remove(index);
          onChanged();
        } else {
          testRepeatedInfo2Builder_.remove(index);
        }
        return this;
      }
      public com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder getTestRepeatedInfo2Builder(
          int index) {
        return getTestRepeatedInfo2FieldBuilder().getBuilder(index);
      }
      public com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder getTestRepeatedInfo2OrBuilder(
          int index) {
        if (testRepeatedInfo2Builder_ == null) {
          return testRepeatedInfo2_.get(index);  } else {
          return testRepeatedInfo2Builder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder> 
           getTestRepeatedInfo2OrBuilderList() {
        if (testRepeatedInfo2Builder_ != null) {
          return testRepeatedInfo2Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(testRepeatedInfo2_);
        }
      }
      public com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder addTestRepeatedInfo2Builder() {
        return getTestRepeatedInfo2FieldBuilder().addBuilder(
            com.dh.game.vo.common.TestProto.TestRepeatedInfo2.getDefaultInstance());
      }
      public com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder addTestRepeatedInfo2Builder(
          int index) {
        return getTestRepeatedInfo2FieldBuilder().addBuilder(
            index, com.dh.game.vo.common.TestProto.TestRepeatedInfo2.getDefaultInstance());
      }
      public java.util.List<com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder> 
           getTestRepeatedInfo2BuilderList() {
        return getTestRepeatedInfo2FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dh.game.vo.common.TestProto.TestRepeatedInfo2, com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder, com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder> 
          getTestRepeatedInfo2FieldBuilder() {
        if (testRepeatedInfo2Builder_ == null) {
          testRepeatedInfo2Builder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dh.game.vo.common.TestProto.TestRepeatedInfo2, com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder, com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder>(
                  testRepeatedInfo2_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          testRepeatedInfo2_ = null;
        }
        return testRepeatedInfo2Builder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.common.testRepeatResp)
    }
    
    static {
      defaultInstance = new testRepeatResp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.common.testRepeatResp)
  }
  
  public interface TestRepeatedInfo2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 d = 1;
    boolean hasD();
    int getD();
  }
  public static final class TestRepeatedInfo2 extends
      com.google.protobuf.GeneratedMessage
      implements TestRepeatedInfo2OrBuilder {
    // Use TestRepeatedInfo2.newBuilder() to construct.
    private TestRepeatedInfo2(Builder builder) {
      super(builder);
    }
    private TestRepeatedInfo2(boolean noInit) {}
    
    private static final TestRepeatedInfo2 defaultInstance;
    public static TestRepeatedInfo2 getDefaultInstance() {
      return defaultInstance;
    }
    
    public TestRepeatedInfo2 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_TestRepeatedInfo2_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_TestRepeatedInfo2_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 d = 1;
    public static final int D_FIELD_NUMBER = 1;
    private int d_;
    public boolean hasD() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getD() {
      return d_;
    }
    
    private void initFields() {
      d_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasD()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, d_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, d_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatedInfo2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.common.TestProto.TestRepeatedInfo2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.common.TestProto.TestRepeatedInfo2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_TestRepeatedInfo2_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_TestRepeatedInfo2_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.common.TestProto.TestRepeatedInfo2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        d_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.common.TestProto.TestRepeatedInfo2.getDescriptor();
      }
      
      public com.dh.game.vo.common.TestProto.TestRepeatedInfo2 getDefaultInstanceForType() {
        return com.dh.game.vo.common.TestProto.TestRepeatedInfo2.getDefaultInstance();
      }
      
      public com.dh.game.vo.common.TestProto.TestRepeatedInfo2 build() {
        com.dh.game.vo.common.TestProto.TestRepeatedInfo2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.common.TestProto.TestRepeatedInfo2 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.common.TestProto.TestRepeatedInfo2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.common.TestProto.TestRepeatedInfo2 buildPartial() {
        com.dh.game.vo.common.TestProto.TestRepeatedInfo2 result = new com.dh.game.vo.common.TestProto.TestRepeatedInfo2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.d_ = d_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.common.TestProto.TestRepeatedInfo2) {
          return mergeFrom((com.dh.game.vo.common.TestProto.TestRepeatedInfo2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.common.TestProto.TestRepeatedInfo2 other) {
        if (other == com.dh.game.vo.common.TestProto.TestRepeatedInfo2.getDefaultInstance()) return this;
        if (other.hasD()) {
          setD(other.getD());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasD()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              d_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 d = 1;
      private int d_ ;
      public boolean hasD() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getD() {
        return d_;
      }
      public Builder setD(int value) {
        bitField0_ |= 0x00000001;
        d_ = value;
        onChanged();
        return this;
      }
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000001);
        d_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.common.TestRepeatedInfo2)
    }
    
    static {
      defaultInstance = new TestRepeatedInfo2(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.common.TestRepeatedInfo2)
  }
  
  public interface TestRepeatInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 i = 1;
    boolean hasI();
    int getI();
  }
  public static final class TestRepeatInfo extends
      com.google.protobuf.GeneratedMessage
      implements TestRepeatInfoOrBuilder {
    // Use TestRepeatInfo.newBuilder() to construct.
    private TestRepeatInfo(Builder builder) {
      super(builder);
    }
    private TestRepeatInfo(boolean noInit) {}
    
    private static final TestRepeatInfo defaultInstance;
    public static TestRepeatInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public TestRepeatInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_TestRepeatInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_TestRepeatInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 i = 1;
    public static final int I_FIELD_NUMBER = 1;
    private int i_;
    public boolean hasI() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getI() {
      return i_;
    }
    
    private void initFields() {
      i_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasI()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, i_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, i_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.common.TestProto.TestRepeatInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.common.TestProto.TestRepeatInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.common.TestProto.TestRepeatInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_TestRepeatInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.common.TestProto.internal_static_com_dh_game_vo_common_TestRepeatInfo_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.common.TestProto.TestRepeatInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        i_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.common.TestProto.TestRepeatInfo.getDescriptor();
      }
      
      public com.dh.game.vo.common.TestProto.TestRepeatInfo getDefaultInstanceForType() {
        return com.dh.game.vo.common.TestProto.TestRepeatInfo.getDefaultInstance();
      }
      
      public com.dh.game.vo.common.TestProto.TestRepeatInfo build() {
        com.dh.game.vo.common.TestProto.TestRepeatInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.common.TestProto.TestRepeatInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.common.TestProto.TestRepeatInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.common.TestProto.TestRepeatInfo buildPartial() {
        com.dh.game.vo.common.TestProto.TestRepeatInfo result = new com.dh.game.vo.common.TestProto.TestRepeatInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.i_ = i_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.common.TestProto.TestRepeatInfo) {
          return mergeFrom((com.dh.game.vo.common.TestProto.TestRepeatInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.common.TestProto.TestRepeatInfo other) {
        if (other == com.dh.game.vo.common.TestProto.TestRepeatInfo.getDefaultInstance()) return this;
        if (other.hasI()) {
          setI(other.getI());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasI()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              i_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 i = 1;
      private int i_ ;
      public boolean hasI() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getI() {
        return i_;
      }
      public Builder setI(int value) {
        bitField0_ |= 0x00000001;
        i_ = value;
        onChanged();
        return this;
      }
      public Builder clearI() {
        bitField0_ = (bitField0_ & ~0x00000001);
        i_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.common.TestRepeatInfo)
    }
    
    static {
      defaultInstance = new TestRepeatInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.common.TestRepeatInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_common_testRepeatResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_common_testRepeatResp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_common_TestRepeatedInfo2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_common_TestRepeatedInfo2_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_common_TestRepeatInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_common_TestRepeatInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n com/proto/common/TestProto.proto\022\025com." +
      "dh.game.vo.common\"\224\001\n\016testRepeatResp\022=\n\016" +
      "testRepeatInfo\030\001 \003(\0132%.com.dh.game.vo.co" +
      "mmon.TestRepeatInfo\022C\n\021testRepeatedInfo2" +
      "\030\002 \003(\0132(.com.dh.game.vo.common.TestRepea" +
      "tedInfo2\"\036\n\021TestRepeatedInfo2\022\t\n\001d\030\001 \002(\005" +
      "\"\033\n\016TestRepeatInfo\022\t\n\001i\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dh_game_vo_common_testRepeatResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dh_game_vo_common_testRepeatResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_common_testRepeatResp_descriptor,
              new java.lang.String[] { "TestRepeatInfo", "TestRepeatedInfo2", },
              com.dh.game.vo.common.TestProto.testRepeatResp.class,
              com.dh.game.vo.common.TestProto.testRepeatResp.Builder.class);
          internal_static_com_dh_game_vo_common_TestRepeatedInfo2_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dh_game_vo_common_TestRepeatedInfo2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_common_TestRepeatedInfo2_descriptor,
              new java.lang.String[] { "D", },
              com.dh.game.vo.common.TestProto.TestRepeatedInfo2.class,
              com.dh.game.vo.common.TestProto.TestRepeatedInfo2.Builder.class);
          internal_static_com_dh_game_vo_common_TestRepeatInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_dh_game_vo_common_TestRepeatInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_common_TestRepeatInfo_descriptor,
              new java.lang.String[] { "I", },
              com.dh.game.vo.common.TestProto.TestRepeatInfo.class,
              com.dh.game.vo.common.TestProto.TestRepeatInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
