// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/proto/shop/YunZiFuProto.proto

package com.dh.game.vo.item;

public final class YunZiFuProto {
  private YunZiFuProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GoldIngotsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 serialId = 1;
    boolean hasSerialId();
    int getSerialId();
    
    // required int32 count = 2;
    boolean hasCount();
    int getCount();
  }
  public static final class GoldIngotsRequest extends
      com.google.protobuf.GeneratedMessage
      implements GoldIngotsRequestOrBuilder {
    // Use GoldIngotsRequest.newBuilder() to construct.
    private GoldIngotsRequest(Builder builder) {
      super(builder);
    }
    private GoldIngotsRequest(boolean noInit) {}
    
    private static final GoldIngotsRequest defaultInstance;
    public static GoldIngotsRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public GoldIngotsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GoldIngotsRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GoldIngotsRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 serialId = 1;
    public static final int SERIALID_FIELD_NUMBER = 1;
    private int serialId_;
    public boolean hasSerialId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSerialId() {
      return serialId_;
    }
    
    // required int32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCount() {
      return count_;
    }
    
    private void initFields() {
      serialId_ = 0;
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSerialId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serialId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serialId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GoldIngotsRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GoldIngotsRequest_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serialId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest.getDescriptor();
      }
      
      public com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest getDefaultInstanceForType() {
        return com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest.getDefaultInstance();
      }
      
      public com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest build() {
        com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest buildPartial() {
        com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest result = new com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serialId_ = serialId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest) {
          return mergeFrom((com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest other) {
        if (other == com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest.getDefaultInstance()) return this;
        if (other.hasSerialId()) {
          setSerialId(other.getSerialId());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSerialId()) {
          
          return false;
        }
        if (!hasCount()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serialId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 serialId = 1;
      private int serialId_ ;
      public boolean hasSerialId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSerialId() {
        return serialId_;
      }
      public Builder setSerialId(int value) {
        bitField0_ |= 0x00000001;
        serialId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSerialId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serialId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 count = 2;
      private int count_ ;
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCount() {
        return count_;
      }
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.item.GoldIngotsRequest)
    }
    
    static {
      defaultInstance = new GoldIngotsRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.item.GoldIngotsRequest)
  }
  
  public interface GoldIngotsResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string urlparams = 1;
    boolean hasUrlparams();
    String getUrlparams();
  }
  public static final class GoldIngotsResponse extends
      com.google.protobuf.GeneratedMessage
      implements GoldIngotsResponseOrBuilder {
    // Use GoldIngotsResponse.newBuilder() to construct.
    private GoldIngotsResponse(Builder builder) {
      super(builder);
    }
    private GoldIngotsResponse(boolean noInit) {}
    
    private static final GoldIngotsResponse defaultInstance;
    public static GoldIngotsResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public GoldIngotsResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GoldIngotsResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GoldIngotsResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string urlparams = 1;
    public static final int URLPARAMS_FIELD_NUMBER = 1;
    private java.lang.Object urlparams_;
    public boolean hasUrlparams() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUrlparams() {
      java.lang.Object ref = urlparams_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          urlparams_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlparamsBytes() {
      java.lang.Object ref = urlparams_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        urlparams_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      urlparams_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUrlparams()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUrlparamsBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUrlparamsBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GoldIngotsResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GoldIngotsResponse_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        urlparams_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse.getDescriptor();
      }
      
      public com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse getDefaultInstanceForType() {
        return com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse.getDefaultInstance();
      }
      
      public com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse build() {
        com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse buildPartial() {
        com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse result = new com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.urlparams_ = urlparams_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse) {
          return mergeFrom((com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse other) {
        if (other == com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse.getDefaultInstance()) return this;
        if (other.hasUrlparams()) {
          setUrlparams(other.getUrlparams());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUrlparams()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              urlparams_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string urlparams = 1;
      private java.lang.Object urlparams_ = "";
      public boolean hasUrlparams() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUrlparams() {
        java.lang.Object ref = urlparams_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          urlparams_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrlparams(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        urlparams_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrlparams() {
        bitField0_ = (bitField0_ & ~0x00000001);
        urlparams_ = getDefaultInstance().getUrlparams();
        onChanged();
        return this;
      }
      void setUrlparams(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        urlparams_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.item.GoldIngotsResponse)
    }
    
    static {
      defaultInstance = new GoldIngotsResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.item.GoldIngotsResponse)
  }
  
  public interface GetYellowTokenOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string actid = 1;
    boolean hasActid();
    String getActid();
    
    // required string token = 2;
    boolean hasToken();
    String getToken();
    
    // required string mid = 3;
    boolean hasMid();
    String getMid();
  }
  public static final class GetYellowToken extends
      com.google.protobuf.GeneratedMessage
      implements GetYellowTokenOrBuilder {
    // Use GetYellowToken.newBuilder() to construct.
    private GetYellowToken(Builder builder) {
      super(builder);
    }
    private GetYellowToken(boolean noInit) {}
    
    private static final GetYellowToken defaultInstance;
    public static GetYellowToken getDefaultInstance() {
      return defaultInstance;
    }
    
    public GetYellowToken getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GetYellowToken_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GetYellowToken_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string actid = 1;
    public static final int ACTID_FIELD_NUMBER = 1;
    private java.lang.Object actid_;
    public boolean hasActid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getActid() {
      java.lang.Object ref = actid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          actid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getActidBytes() {
      java.lang.Object ref = actid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        actid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string token = 2;
    public static final int TOKEN_FIELD_NUMBER = 2;
    private java.lang.Object token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          token_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string mid = 3;
    public static final int MID_FIELD_NUMBER = 3;
    private java.lang.Object mid_;
    public boolean hasMid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getMid() {
      java.lang.Object ref = mid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMidBytes() {
      java.lang.Object ref = mid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      actid_ = "";
      token_ = "";
      mid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasActid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getActidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTokenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getActidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTokenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.GetYellowToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.item.YunZiFuProto.GetYellowToken prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.item.YunZiFuProto.GetYellowTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GetYellowToken_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_GetYellowToken_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.item.YunZiFuProto.GetYellowToken.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        actid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        mid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.item.YunZiFuProto.GetYellowToken.getDescriptor();
      }
      
      public com.dh.game.vo.item.YunZiFuProto.GetYellowToken getDefaultInstanceForType() {
        return com.dh.game.vo.item.YunZiFuProto.GetYellowToken.getDefaultInstance();
      }
      
      public com.dh.game.vo.item.YunZiFuProto.GetYellowToken build() {
        com.dh.game.vo.item.YunZiFuProto.GetYellowToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.item.YunZiFuProto.GetYellowToken buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.item.YunZiFuProto.GetYellowToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.item.YunZiFuProto.GetYellowToken buildPartial() {
        com.dh.game.vo.item.YunZiFuProto.GetYellowToken result = new com.dh.game.vo.item.YunZiFuProto.GetYellowToken(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.actid_ = actid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mid_ = mid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.item.YunZiFuProto.GetYellowToken) {
          return mergeFrom((com.dh.game.vo.item.YunZiFuProto.GetYellowToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.item.YunZiFuProto.GetYellowToken other) {
        if (other == com.dh.game.vo.item.YunZiFuProto.GetYellowToken.getDefaultInstance()) return this;
        if (other.hasActid()) {
          setActid(other.getActid());
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasMid()) {
          setMid(other.getMid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasActid()) {
          
          return false;
        }
        if (!hasToken()) {
          
          return false;
        }
        if (!hasMid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              actid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              token_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              mid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string actid = 1;
      private java.lang.Object actid_ = "";
      public boolean hasActid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getActid() {
        java.lang.Object ref = actid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          actid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setActid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        actid_ = value;
        onChanged();
        return this;
      }
      public Builder clearActid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        actid_ = getDefaultInstance().getActid();
        onChanged();
        return this;
      }
      void setActid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        actid_ = value;
        onChanged();
      }
      
      // required string token = 2;
      private java.lang.Object token_ = "";
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      void setToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
      }
      
      // required string mid = 3;
      private java.lang.Object mid_ = "";
      public boolean hasMid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getMid() {
        java.lang.Object ref = mid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mid_ = value;
        onChanged();
        return this;
      }
      public Builder clearMid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mid_ = getDefaultInstance().getMid();
        onChanged();
        return this;
      }
      void setMid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        mid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.item.GetYellowToken)
    }
    
    static {
      defaultInstance = new GetYellowToken(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.item.GetYellowToken)
  }
  
  public interface YellowLevelGiftRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
  }
  public static final class YellowLevelGiftRequest extends
      com.google.protobuf.GeneratedMessage
      implements YellowLevelGiftRequestOrBuilder {
    // Use YellowLevelGiftRequest.newBuilder() to construct.
    private YellowLevelGiftRequest(Builder builder) {
      super(builder);
    }
    private YellowLevelGiftRequest(boolean noInit) {}
    
    private static final YellowLevelGiftRequest defaultInstance;
    public static YellowLevelGiftRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public YellowLevelGiftRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_YellowLevelGiftRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_YellowLevelGiftRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_YellowLevelGiftRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dh.game.vo.item.YunZiFuProto.internal_static_com_dh_game_vo_item_YellowLevelGiftRequest_fieldAccessorTable;
      }
      
      // Construct using com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest.getDescriptor();
      }
      
      public com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest getDefaultInstanceForType() {
        return com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest.getDefaultInstance();
      }
      
      public com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest build() {
        com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest buildPartial() {
        com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest result = new com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest) {
          return mergeFrom((com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest other) {
        if (other == com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dh.game.vo.item.YellowLevelGiftRequest)
    }
    
    static {
      defaultInstance = new YellowLevelGiftRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dh.game.vo.item.YellowLevelGiftRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_item_GoldIngotsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_item_GoldIngotsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_item_GoldIngotsResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_item_GoldIngotsResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_item_GetYellowToken_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_item_GetYellowToken_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dh_game_vo_item_YellowLevelGiftRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dh_game_vo_item_YellowLevelGiftRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!com/proto/shop/YunZiFuProto.proto\022\023com" +
      ".dh.game.vo.item\"4\n\021GoldIngotsRequest\022\020\n" +
      "\010serialId\030\001 \002(\005\022\r\n\005count\030\002 \002(\005\"\'\n\022GoldIn" +
      "gotsResponse\022\021\n\turlparams\030\001 \002(\t\";\n\016GetYe" +
      "llowToken\022\r\n\005actid\030\001 \002(\t\022\r\n\005token\030\002 \002(\t\022" +
      "\013\n\003mid\030\003 \002(\t\"$\n\026YellowLevelGiftRequest\022\n" +
      "\n\002id\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dh_game_vo_item_GoldIngotsRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dh_game_vo_item_GoldIngotsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_item_GoldIngotsRequest_descriptor,
              new java.lang.String[] { "SerialId", "Count", },
              com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest.class,
              com.dh.game.vo.item.YunZiFuProto.GoldIngotsRequest.Builder.class);
          internal_static_com_dh_game_vo_item_GoldIngotsResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dh_game_vo_item_GoldIngotsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_item_GoldIngotsResponse_descriptor,
              new java.lang.String[] { "Urlparams", },
              com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse.class,
              com.dh.game.vo.item.YunZiFuProto.GoldIngotsResponse.Builder.class);
          internal_static_com_dh_game_vo_item_GetYellowToken_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_dh_game_vo_item_GetYellowToken_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_item_GetYellowToken_descriptor,
              new java.lang.String[] { "Actid", "Token", "Mid", },
              com.dh.game.vo.item.YunZiFuProto.GetYellowToken.class,
              com.dh.game.vo.item.YunZiFuProto.GetYellowToken.Builder.class);
          internal_static_com_dh_game_vo_item_YellowLevelGiftRequest_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_dh_game_vo_item_YellowLevelGiftRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dh_game_vo_item_YellowLevelGiftRequest_descriptor,
              new java.lang.String[] { "Id", },
              com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest.class,
              com.dh.game.vo.item.YunZiFuProto.YellowLevelGiftRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
